### PR TITLE
Allow to pass a -u supergraph url for demo purposes.

### PR DESCRIPTION
**Pull request by o0Ignition0o**
This commit adds a -u flag so the demo example becomes "router -u https://supergraph.demo.starstuff.dev/"

This eases the initial setup first exploration steps.

### CODE REVIEW

**Review by garypen — COMMENTED** [review]
Some high level questions:
 - what happens if you specify both -u and -s? In fact, isn't -u just a superset of -s.
 - what happens if you specify -w with -u? Does it work?

What I'm really trying to make sure is that we don't just throw in (-u) and then have to figure out later how it interacts with other flags. I feel like we should be able to make (-s) redundant with the (-u) flag and I want to make sure that there are no surprises with flag interactions.

**Comment by o0Ignition0o** [comment]
Oh that's a very good comment, we could check whether -s points to a path or a url, and do the right thing accordingly.

What your comment hints at is that maybe it's not such a small and impactless change after all, and maybe it's worth raising an issue instead

**Review by abernix — CHANGES_REQUESTED** [review]
Interesting idea!  I'm not sure if this quite the right direction though as I'm actually not sure if this sets the precedent we want for users / DX / UX on the grander scheme of things.  In particular, I think having users be intimately familiar with `--supergraph` (and its hot-reload-ability) **and** `rover`'s ability to fetch graphs from the registry is an important ergonomic for users to understand.

Practically speaking, I _don't_ think we want supergraphs to generally be in the public un-authenticated space on the internet, which I think means that this flag almost entirely serves the purpose of getting the demo supergraph.  Of course, a natural follow-up could be that we add various CLI flags and stuff to the `router` to enable various ways of — e.g., passing headers to the endpoint, but I think that's getting away from our mission.

Further, because `--supergraph` has file-watching/hot-reloading functionality, I think this it begs the question if this flag should behave similarly (e.g., via polling?).  By and large though, I think it internalizes the schema fetching mechanism into the Router in a way that, Product-wise, we have seen as being something that should be done externally (via `rover`, ideally) or via the internal Uplink mechanism to the Registry. 

Perhaps other another approach would be to bake-in/hard-code the use for _exactly_ the `https://supergraph.demo.starstuff.dev/` (and not open the door to a wall of HTTP knobs, instead only optimizing for our demo use-case)?

Or perhaps — as an evolution to that previous possibility — maybe we should just have `rover supergraph` fetch work on a published, **public** variant of our demo supergraph, to enable users to familiarize themselves with `rover` at the same time?

No code changes requested, but I'm marking this as Request changes on account of this needing discussion.

**Comment by abernix** [comment]
@o0Ignition0o One suggestion would be a Discussion (or an Issue, but it seems we're okay with Discussions) about the more general conversation of a "Getting Started" experience: That could touch on having `rover` run the Router, or it could offer short term things, like allowing `--supergraph` to accept `STDIN` (and thus enabling something like `curl -ssL https://go.apollo.dev/r/supergraph | ./router -s -`).

**Comment by o0Ignition0o** [comment]
opened #468 so we can discuss it further

**Pull request closed without merging**
