### PR TITLE
do not recalculate DashMap's default shard amount on every new map

### LINKED ISSUE #1366: investigate Context's syscalls usage
creating a new `Context` object surprisingly implies doing a file syscall:
Screenshot from 2022-07-06 16-37-14

This is apparently due to `DashMap` looking up the available resources in the cgroup at creation:
https://github.com/xacrimon/dashmap/blob/459db7ac6f3d0b46f507cb724dd9bb0ce389f4ae/src/lib.rs#L55

I opened https://github.com/xacrimon/dashmap/issues/219 to see if this could be memoized. If not we could do it inside the router

### PR DESCRIPTION
**Pull request by Geal**
Fix #1366

small optimization that will reduce the number of syscalls (Dashmap recalculates the shard amount from the cgroup at creation but does not save the value anywhere)

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]

**Comment by Geal** [comment]
perf test please

**Comment by Geal** [comment]
perf test please

**Comment by o0Ignition0o** [comment]
perf test please

**Comment by Geal** [comment]
this will be replaced by the fix for https://github.com/xacrimon/dashmap/issues/219 directly in dashmap

**Comment by Geal** [comment]
closing this because DashMap 5.4.0 was released on added to the router in https://github.com/apollographql/router/commit/01512853c25441b1dcd58a51562aa8677e37b73e

**Pull request closed without merging**
