### PR TITLE
fix configuration file in docs

### PR DESCRIPTION
**Pull request by Geal**
it was not matching the configuration loader

also mark the username and password fields as not skipped so they can be
used from the config file

### CODE REVIEW

**Comment by cecton** [comment]
> I think He meant a custom `impl Display` with a `tracing::debug!("configuration is {}", config)` statement at startup

You want to enforce the trait Display on the entire Configuration struct? :D good luck with that. Besides, you still need to redact in the Debug impl

**Comment by prasek** [comment]
I'm still not able to get otel tracing working with the updated config - see https://github.com/apollographql/router/issues/149 for repro steps. Thx.

**Comment by o0Ignition0o** [comment]
friendly ping here, I'm trying to clean up the in flight PRs.

Can we close this now that #120 has been merged?

Should we open an issue wrt phil's comment?

**Comment by Geal** [comment]
it was fixed by https://github.com/apollographql/router/issues/149#issuecomment-971565736

We should probably open another issue for the config file versus env var debate, and close this PR

**Comment by cecton** [comment]
> We should probably open another issue for the config file versus env var debate, and close this PR

Let's move that to the existing discussion with the parameter in configuration vs cli. I think it is all related because we might want to have a mechanism that handles the 3: parameters coming from cli, coming from configuration file, coming from env variables.

> also mark the username and password fields as not skipped so they can be used from the config file

That part though I'm not sure is related to the same discussion because it's more about security and what should be allowed. Maybe open another discussion targeting specifically for username and password parameters?

**Comment by Geal** [comment]
sure

**Comment by Geal** [comment]
https://github.com/apollographql/router/discussions/197 for the big environment variables debate :)

**Comment by cecton** [comment]
let them fight

**Pull request closed without merging**
