### PR TITLE
Fix usage reporting of enum values in deferred requests

### PR DESCRIPTION
**Pull request by bonnici**
Fixes reporting of the enum values from responses in extended references for deferred requests. Deferred requests include two passes through the format response function, so we need to add to an existing map of enums rather than overwriting it on each pass. We also clear the map when submitting a report so that subscription reports only include the enum values referenced in responses from the particular query in the subscription request/event.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Review by bnjjj — APPROVED** [review]
Does it need a changelog @bonnici ?

**Comment by bonnici** [comment]
> Does it need a changelog @bonnici ?

@bnjjj I can add one if it's needed but I don't really know the policy here. It's basically a bug fix.

**Comment by bnjjj** [comment]
@bonnici I'm just asking if we need it. Do you think it's something that would be relevant for our customers to know ?If so let's create a changelog entry. If not then we don't need to do anything

**Comment by bonnici** [comment]
Ah ok, I don't think it's needed then. This wasn't based on a customer request and the feature hasn't been enabled widely yet so I don't think anyone would know the bug exists yet.

**Pull request merged**
