### PR TITLE
Rename pipeline stages

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/apollographql/router/issues/1138

### CODE REVIEW

**Review by garypen — APPROVED** [review]
Nice!

**Review by o0Ignition0o — APPROVED** [review]
LGTM gogogo before there s new conflicts :D

**Comment by SimonSapin** [comment]
There’s a new conflict 🤦

**Comment by o0Ignition0o** [comment]
> There’s a new conflict 🤦

https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia1.tenor.com%2Fimages%2F3f15a0a8771c2df66d081c76f830d80c%2Ftenor.gif%3Fitemid%3D18379274&f=1&nofb=1

**Pull request merged**
