### PR TITLE
Disable windows defender in CI for performance

### PR DESCRIPTION
**Pull request by BrynCooke**

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
I don't think this makes a difference

**Pull request closed without merging**
