### PR TITLE
Warn on missing docs, with allow exceptions to be removed progressively

### PR DESCRIPTION
**Pull request by SimonSapin**
Part of https://github.com/apollographql/router/issues/799

### CODE REVIEW

**Review by abernix — COMMENTED** [review]
Nice! Would it make sense to open an open an umbrella issue with ... idk, TODO-like checkboxes that identify the `FIXME` locations which were introduced in this PR.  We could keep that on the board as a longer-running tracking issue and then we can break out specific items into subtasks as we have spare cycles?

**Comment by SimonSapin** [comment]
https://github.com/apollographql/router/issues/799 can be that umbrella issue. I can add a checklist but I’m worried it’ll be perpetually out of date (whereas `grep allow.*missing_docs` won’t).

**Review by garypen — COMMENTED** [review]
I note that auto-merge on approve is enabled, so I want to approve, but I'd better wait for other reviews before I do.

**Comment by SimonSapin** [comment]
I’ve added a checklist to https://github.com/apollographql/router/issues/799, with a note saying it’s up to date as of this PR.

**Review by o0Ignition0o — APPROVED** [review]

**Pull request merged**
