### PR TITLE
replace the BatchSpanProcessor with SimpleSpanProcessor

### LINKED ISSUE #2046: Using the SimpleSpanExporter instead of BatchSpanExporter
we currently have issues with telemetry when the traffic increases, where some traces are missing, some traces are missing spans, and we can see logs like this:

```
2022-11-04T09:42:50.805799Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
2022-11-04T09:42:57.097444Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
2022-11-04T09:42:57.299729Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
```

For some context, the rust-opentelemetry crate separates the span processor, that records and aggregates spans, and the exporter, that is specific to the collector service (otlp, jaeger, datadog...). The [SimpleSpanProcessor documentation](https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/trace/struct.SimpleSpanProcessor.html) indicates `Note that the simple processor exports synchronously every time a span is ended. If you find this limiting, consider the batch processor instead`. So, in fear of scalability issues, we went with the [BatchSpanProcessor](https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/struct.BatchSpanProcessor.html). The `BatchSpanProcessor` works by starting a separate task that receives spans over a channel, so any other task that creates spans  sneds them directly and does not do anymore processing.

In theory the `BatchSpanProcessor` should give us better performance, but my hunch here was that with one central task handling spans created by a lot of concurrent requests, we are instead creating a bottleneck that will quickly get overloaded. And so by using the `SimpleSpanProcessor` instead, we could better handle the load, at the cost of CPU usage and more latency.

# Benchmarks

So I tested this idea by reproducing our CI benchmarks, with the "products" and "reviews" subgraphs, and the 5kB query, that generates 24 spans per query. I perform 100000 requests with 10 clients (it's not much because it's really easy to make the batch processor fall over, and sampling traces does not change anything). The router has 3 cores available.

## BatchSpanProcessor

(I removed the error log before compiling because it was taking too much time)

`hey` results:

```
Summary:                                                  
  Total:        77.0854 secs                              
  Slowest:      0.0351 secs                               
  Fastest:      0.0055 secs                               
  Average:      0.0077 secs                               
  Requests/sec: 1297.2631                                 
                                                          
                                                          
Response time histogram:                                  
  0.005 [1]     |                                         
  0.008 [92669] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
  0.011 [7261]  |■■■                                      
  0.014 [11]    |                                         
  0.017 [9]     |                                         
  0.020 [15]    |                                         
  0.023 [9]     |                                         
  0.026 [5]     |                                         
  0.029 [3]     |                                         
  0.032 [4]     |                                         
  0.035 [13]    |                                         
                                                          
                                                          
Latency distribution:                                     
  10% in 0.0072 secs                                      
  25% in 0.0074 secs                                      
  50% in 0.0076 secs                                      
  75% in 0.0080 secs                                      
  90% in 0.0083 secs                                      
  95% in 0.0085 secs                                      
  99% in 0.0090 secs                                      
```

Jaeger only receives 2 traces, with 1 span each (the third one is from the initial test query I did separately before benchmarking)

Screenshot from 2022-11-04 11-06-46

The flamegraph shows that we spend 13% of CPU time in the span exporter (the column on the right)

flamegraph-batchspan

Overall the router uses 55% of each core to handle that load

## SimpleSpanProcessor, sampling at 100%

it is slower and latency is less table than the `BatchSpanProcessor`
```
Summary:                                                 
  Total:        90.8695 secs                             
  Slowest:      0.0776 secs                              
  Fastest:      0.0055 secs                              
  Average:      0.0091 secs                              
  Requests/sec: 1100.4789                                
                                                         
                                                         
Response time histogram:                                 
  0.005 [1]     |                                        
  0.013 [96428] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.020 [1408]  |■                                       
  0.027 [1229]  |■                                       
  0.034 [564]   |                                        
  0.042 [242]   |                                        
  0.049 [89]    |                                        
  0.056 [20]    |                                        
  0.063 [9]     |                                        
  0.070 [8]     |                                        
  0.078 [2]     |                                        
                                                         
                                                         
Latency distribution:                                    
  10% in 0.0078 secs                                     
  25% in 0.0081 secs                                     
  50% in 0.0085 secs                                     
  75% in 0.0090 secs                                     
  90% in 0.0096 secs                                     
  95% in 0.0103 secs                                     
  99% in 0.0265 secs                                     
```

But jaeger receives all the traces:

Screenshot from 2022-11-04 11-21-13

We see in the flamegraph that we now spend 20% of CPU time in the `SimpleSpanProcessor`. The router uses 85% of each core to handle that load.

flamegraph-simplespan

So as expected, it is slower and uses more resources, but this is without any sampling.

## SimpleSpanProcessor, sampling at 1%

Same performance as `BatchSpanProcessor`:

```
Summary:                                                  
  Total:        78.1037 secs                              
  Slowest:      0.0260 secs                               
  Fastest:      0.0049 secs                               
  Average:      0.0078 secs                               
  Requests/sec: 1280.3484                                 
                                                          
                                                          
Response time histogram:                                  
  0.005 [1]     |                                         
  0.007 [2550]  |■                                        
  0.009 [96278] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
  0.011 [1099]  |                                         
  0.013 [44]    |                                         
  0.015 [18]    |                                         
  0.018 [1]     |                                         
  0.020 [4]     |                                         
  0.022 [4]     |                                         
  0.024 [0]     |                                         
  0.026 [1]     |                                         
                                                          
                                                          
Latency distribution:                                     
  10% in 0.0072 secs                                      
  25% in 0.0074 secs                                      
  50% in 0.0077 secs                                      
  75% in 0.0081 secs                                      
  90% in 0.0085 secs                                      
  95% in 0.0087 secs                                      
  99% in 0.0092 secs
```

As expected, Jaeger receives less traces, but they are still complete:

Screenshot from 2022-11-04 11-31-53

It is now barely noticeable in the flamegraph (0.5% of CPU time, the column on the left), the router uses 50% of each core

flamegraph

## Conclusion

If we use the `BatchSpanProcessor`, as soon as there's some traffic it breaks and we don't receives traces. With `SimpleSpanProcessor` and trace sampling, we receive full traces and it's as fast as the batch processor

### PR DESCRIPTION
**Pull request by Geal**
Fix #2046

rust-opentelemetry's BatchSpanProcessor does not handle well larger loads, even with sampling: some traces are not sent, some are sent but miss some spans.  Benchmarking has shown that with the SimpleSpanProcessor, all the traces are sent with all their spans, at the cost of some latency and CPU time, but that is easily fixed by sampling.

This also removes the filter span processor, because SimpleSpanProcessor::new is not public, so we cannot create it and apply the filter on it. It is replaces with a span exporter filter, that we can apply directly over the filter

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]

**Review by BrynCooke — CHANGES_REQUESTED** [review]
I think this has actually been tackled already in https://github.com/open-telemetry/opentelemetry-rust/pull/781

BatchSpanProcessor has been modified to allow concurrent exports.
In addition, there are plenty of env variables that can be used to tweak batch span processor behavior. Therefor I don't think we should merge this.

**Comment by Geal** [comment]
As you can see in #2046 when I did more tests it was not clear that this PR really improved things so I agree this shiuld npt be the solution. And the environment variables require way too luch fiddling to get something working.
Could you validate that concurrent exports fix the lost traces and spans issue though?

**Comment by BrynCooke** [comment]
I did some local testing and was able to get from 10rps to 1000rps by fiddling with the batch exporter settings. Concurrency makes a huge difference, but it is still on the onus of the user to work out what will work for them based on their environment.

**Comment by abernix** [comment]
I'm going to close this PR, as it **appears** that the issue that this PR claims to close has been closed [with reason](https://github.com/apollographql/router/issues/2046#issuecomment-1316614121) that seems like it might de-necessitate this PR, as good as it was to try.  There's also commentary above that I think supports closing it.

Feel free to re-open if you feel differently!

**Pull request closed without merging**
