### PR TITLE
experiment with streaming JSON serialization

### PR DESCRIPTION
**Pull request by Geal**
related:
- https://github.com/apollographql/router/issues/173 (streaming serialization)

**still an experiment, not ready to be merged: there are licensing issues, and the streaming serializer will probably end up in serde_json_bytes**

instead of serializing the JSON response to one buffer, that needs to be
reallocated multiple times if it is not large enough, we could serialize
to a serie of small buffers that are sent as soon as they are full.

Apparently it adds some overhead in the smaller percentiles, but overall
results in a more stable latency distribution, and clients can start
parsing and processing data earlier.

I suspect this can have a big impact on larger response sizes

### CODE REVIEW

**Comment by Geal** [comment]
## main 2fe563d
279MB max resident memory usage

Summary:                                                         
  Total:        81.6236 secs                                     
  Slowest:      3.3268 secs                                      
  Fastest:      0.0052 secs                                      
  Average:      0.2601 secs                                      
  Requests/sec: 3675.4057                                        
                                                                 
  Total data:   3576900000 bytes                                 
  Size/request: 11923 bytes                                      
                                                                 
Response time histogram:                                         
  0.005 [1]     |                                                
  0.337 [220261]        |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.669 [26984] |■■■■■                                           
  1.002 [41544] |■■■■■■■■                                        
  1.334 [5006]  |■                                               
  1.666 [4912]  |■                                               
  1.998 [822]   |                                                
  2.330 [386]   |                                                
  2.662 [53]    |                                                
  2.995 [25]    |                                                
  3.327 [6]     |                                                
                                                                 
                                                                 
Latency distribution:                                            
  10% in 0.0482 secs                                             
  25% in 0.0575 secs                                             
  50% in 0.0706 secs                                             
  75% in 0.5126 secs                                             
  90% in 0.7731 secs                                             
  95% in 0.9039 secs                                             
  99% in 1.4855 secs                                             


## PR fceed7f (serializing in spawn_blocking)
221MB res

Summary:                                                          
  Total:        78.9947 secs                                      
  Slowest:      2.2936 secs                                       
  Fastest:      0.0054 secs                                       
  Average:      0.2543 secs                                       
  Requests/sec: 3797.7223                                         
                                                                  
                                                                  
Response time histogram:                                          
  0.005 [1]     |                                                 
  0.234 [196481]        |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
  0.463 [9183]  |■■                                               
  0.692 [77281] |■■■■■■■■■■■■■■■■                                 
  0.921 [9539]  |■■                                               
  1.149 [4442]  |■                                                
  1.378 [2638]  |■                                                
  1.607 [201]   |                                                 
  1.836 [204]   |                                                 
  2.065 [20]    |                                                 
  2.294 [10]    |                                                 
                                                                  
                                                                  
Latency distribution:                                             
  10% in 0.0450 secs                                              
  25% in 0.0549 secs                                              
  50% in 0.0705 secs                                              
  75% in 0.5338 secs                                              
  90% in 0.6480 secs                                              
  95% in 0.7034 secs                                              
  99% in 1.1520 secs                                              


# PR f511dc9 (using tokio's DuplexStream and ReaderStream)

254MB res

Summary:                                                         
  Total:        92.8599 secs                                     
  Slowest:      3.8801 secs                                      
  Fastest:      0.0042 secs                                      
  Average:      0.2965 secs                                      
  Requests/sec: 3230.6749                                        
                                                                 
                                                                 
Response time histogram:                                         
  0.004 [1]     |                                                
  0.392 [209865]        |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.779 [53784] |■■■■■■■■■■                                      
  1.167 [24612] |■■■■■                                           
  1.555 [8765]  |■■                                              
  1.942 [2187]  |                                                
  2.330 [624]   |                                                
  2.717 [127]   |                                                
  3.105 [30]    |                                                
  3.492 [3]     |                                                
  3.880 [2]     |                                                
                                                                 
                                                                 
Latency distribution:                                            
  10% in 0.0543 secs                                             
  25% in 0.0648 secs                                             
  50% in 0.0799 secs                                             
  75% in 0.5947 secs                                             
  90% in 0.8128 secs                                             
  95% in 0.9787 secs                                             
  99% in 1.5526 secs                                             

I suspect that last attempt reallocates a lot instead of using fixed size buffers. It also does not benefit from serde_json_bytes: it would be possible to generate a Stream of Bytes from it without copying too much. That's the next experiment.

**Comment by Geal** [comment]
600 rps with 9540b5f. Probably not the right solution :rofl:

**Comment by Geal** [comment]
alright, I've done enough exploration on this. To sum up:
- current main serializes the response to a Vec (possibly reallocating multiple times), then sends it at once
- b094534 and 760e11e serialize in a blocking task, using a writer that allocates a big vector at once, and sends it through a channel once it's full. We build a hyper `Body` from a stream of buffers. **slightly faster than main, but more importantly: higher p50 but lower p99 (half). latency is much more stable**
- f511dc9 is the async version, serializing manually (without serde) in async. A bit slower, maybe because the serialization function is async and recursive, so allocating lots of futures?
- 9540b5f and 4ca35ce are dead ends. The idea was that the JSON object contains a Bytes for each string, so instead of copying into a buffer we can send those. Unfortunately hyper does not handle well a large number of small buffers, so we get -83% perf
- a53a711 (async) and eb10e5e (sync) refine that idea by serializing to a buffer, but when we get a string larger than the buffer, we flush the current buffer then send the string's Bytes right after

**Comment by Geal** [comment]
digestible benchmark results:

## 12kB responses
(latencies in seconds)

|      | main | sync serializer (serde) | sync serializer (bytes)|
|-----|--- |      ----------------                  | -------------------------     |
|RPS|3606 |3707 | 3697 |
|p10| 0.0496 | 0.0471 | 0.0463 |
|p25|0.0593 | 0.0573 | 0.0570 |
|p50| 0.0723| 0.0719 | 0.0730 |
|p75| 0.3352| 0.5340 | 0.5173 |
|p90| 0.7997 | 0.6866 | 0.6991 |
|p95| 0.9242 | 0.7728 | 0.8255 |
|p99| 1.5285| 1.2849 | 1.2951 |

Both sync serializers are a bit faster, even at higher percentiles

## 28kB responses
(one field is 4096 bytes, it appears multiple times)

|      | main | sync serializer (serde) | sync serializer (bytes)|
|-----|--- |      ----------------                  | -------------------------     |
|RPS| 3411  |  3492  | 3625  |
|p10| 0.0513  | 0.0348  | 0.2501 |
|p25|  0.0617 | 0.0490  |  0.2567 |
|p50|  0.0760 |  0.3199 |  0.2626 |
|p75| 0.4694  |  0.3571  |  0.2692 |
|p90|  0.8327  |  0.6117 |  0.2820 |
|p95|  0.9711  | 0.6482  |  0.3989 |
|p99|  1.5964  | 0.7244  | 0.4319  |

the sync serializer that can pass existing Bytes instances directly instead of copying them fares better on larger responses. p10 and p25 latencies are higher because latency is much more stable, concentrated around 0.26s

**Comment by Geal** [comment]
I'm not sure if there's a way to have the benchmarks run with larger responses (with huge fields), maybe we'll see more impact. At least that's what I saw locally

**Review by bnjjj — APPROVED** [review]

**Comment by Geal** [comment]
performance is still slightly lower than main on small responses :disappointed: 
I know that for larger responses it gives great benefits on latency. Maybe this could be activated by an option?

**Comment by BrynCooke** [comment]
If the perf drop for small responses is marginal then would avoid adding extra config for this. Just enable it by default.

**Comment by Geal** [comment]
here that's a 10% change, that's significant. A thing I could explore though: since the final response size will be roughly the sum of subgraph response sizes, I could gather those sizes in the context, and when serializing the response, deciding based on that number if it should be serialized directly in one buffer, or if it needs to go through streaming serialization

**Comment by abernix** [comment]
We can easily re-open this and restore the branch, if we find we need it in the future, but at this point I think this has been open for a bit too long.

**Pull request closed without merging**
