### PR TITLE
Remove crates directory

### PR DESCRIPTION
**Pull request by cecton**
As per our vote in #201. I'm removing the `crates` directory.

~~@abernix which LICENSE is the correct one? The one in the root repository or the one in the crates? I'm replacing them with symlinks to avoid this issue again (unless the difference of license was intended?)~~ [edit: reverted to their original state as requested]

```patch
--- apollo-router-core/LICENSE  2021-11-24 11:31:03.969446027 +0100
+++ LICENSE     2021-11-10 15:12:35.318018845 +0100
@@ -1,5 +1,12 @@
 Copyright 2021 Apollo Graph, Inc.
 
+Source code in this repository is covered by the Elastic License 2.0. The
+default throughout the repository is a license under the Elastic License 2.0,
+unless a file header or a license file in a subdirectory specifies another
+license.
+
+--------------------------------------------------------------------------------
+
 Elastic License 2.0
 
 ## Acceptance
@@ -92,4 +99,4 @@
 
 **trademark** means trademarks, service marks, and similar rights.
 
---------------------------------------------------------------------------------
\ No newline at end of file
+--------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by abernix** [comment]
@cecton The difference was intentional.  We can revisit it when it return on Monday if we'd like to change it and I can explain some relevance then too.

**Comment by abernix** [comment]
Please just don't use the symlinks, and instead just preserve the difference (root stays as it is and the crates stay as they are)

**Comment by cecton** [comment]
Ok thanks

**Review by o0Ignition0o — APPROVED** [review]
+1 if there's no symlinks, I have no idea how to make sure there isn't any.

**Comment by cecton** [comment]
> +1 if there's no symlinks, I have no idea how to make sure there isn't any.

It would be clearly shown in the PR "files" tab.

**Review by Geal — APPROVED** [review]

**Pull request merged**
