### PR TITLE
[next] Remove --apollo-uplink-poll-interval

### PR DESCRIPTION
**Pull request by goto-bus-stop**
This is targeting Router 2.0.

`--apollo-uplink-poll-interval` does not do a lot today. It's supposed to configure the interval between polls of Apollo Uplink to retrieve new configuration or a new supergraph schema. But after one poll, Uplink responds with a new delay, which is used going forward. So in effect this only configures the *initial poll*, which is certainly not expected.

**Open questions**
- [ ] While removing this I saw that the poll interval value is used if you provide URLs for the supergraph schema source with hot_reload. Should we continue to support that?
- [x] Should I document this change somewhere? Do we have a migration document? Or should I just use a changeset?

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

There were no tests for this feature

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

[ROUTER-825]: https://apollographql.atlassian.net/browse/ROUTER-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]
The migration guide https://github.com/apollographql/router/blob/next/docs/source/reference/migration/from-router-v1.mdx

**Review by garypen — DISMISSED** [review]
As discussed: Please add details of the removal to the migration guide so we don't lose visibility of this change.

**Comment by goto-bus-stop** [comment]
I added a new section for "Removed features" in the migration guide.

**Review by garypen — COMMENTED** [review]
I don't understand this question:
```
While removing this I saw that the poll interval value is used if you provide URLs for the supergraph schema source with hot_reload. Should we continue to support that?
```
But if you supply an URL (I'm assuming you mean using the -s flag) how would the interval be used? The files provided via -s interact with a File Watcher which has its own default watching duration.

**Comment by goto-bus-stop** [comment]
I'm not entirely sure what it is or if or how anyone uses it. But this is what I'm referring to:
https://github.com/apollographql/router/blob/ba697567927f0b0fe52fec56663ac51219ed039f/apollo-router/src/executable.rs#L202-L204

If you provide `--supergraph-urls`, you get a `SchemaSource::URLs` that re-fetches every `--apollo-uplink-poll-interval` seconds: (snippet is from this branch, so already modified to the hardcoded INITIAL_UPLINK_POLL_INTERVAL)
https://github.com/apollographql/router/blob/ba697567927f0b0fe52fec56663ac51219ed039f/apollo-router/src/executable.rs#L545-L554

**Pull request merged**
