### PR TITLE
Do not fail JWT plugin init on JWKS download

### LINKED ISSUE #2747: Auth plugin should not fail on init if provider is uncontactable or returns a bad response
The jwks plugin may return an error on init even if it is correctly configured. This causes the router to fail to start or fail to reload.

Not all requests need to be authenticated, so probably this should not fail init but on request.

### PR DESCRIPTION
**Pull request by Geal**
Fix #2747

JWKS download can fail sometimes, but it can be temporary, so it should not fail plugin initialization. We still try to download them during init, to make a reasonable effort of starting a router with all the JWKs, but if one download fails we still go on

### CODE REVIEW

**Comment by BrynCooke** [comment]
The initial call to poll should probably be done with an owned write lock on `jwks_map`.
That way any call to iterate over the inside `Iter` the call to `self.manager.jwks_map.read()` will have to wait for the initial call to poll to finish.

Otherwise there will be a period between the router reloading and requests not being authenticated correctly as the initial jwks has not been received.

**Comment by Geal** [comment]
Here the plugin init does not finish until the initial load is done so when this configuration starts receiving traffic, it should have the jwks available in most cases

**Comment by BrynCooke** [comment]
Should we wait on `tokio::task::spawn(poll(list.clone(), jwks_map.clone(), drop_receiver));` then?

**Comment by Geal** [comment]
No, this is done above in the join_all. Poll does more or less the same thing, but in a loop, and adding sleeps

**Review by BrynCooke — APPROVED** [review]

**Pull request merged**
