### PR TITLE
replace startup with ctor for plugin registration

### PR DESCRIPTION
**Pull request by garypen**
I've implemented the change so that we declare a function in private scope to register each plugin.

fixes: #1703

### CODE REVIEW

**Review by BrynCooke — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]

**Comment by SimonSapin** [comment]
To avoid the naming constraint, would this work?

```rust
const _: () = { //  Artificial scope to avoid naming collisions
    #[$crate::_private::ctor::ctor]
    fn register() { // no need to come up with a unique name
        // …
    }
};

**Comment by garypen** [comment]
> To avoid the naming constraint, would this work?
> 
> ```rust
> const _: () = { //  Artificial scope to avoid naming collisions
>     #[$crate::_private::ctor::ctor]
>     fn register() { // no need to come up with a unique name
>         // …
>     }
> };
> ```

Not quite. We have tests which declare multiple plugins from the same file, so that would result in multiple `register` functions.
Details:
apollo-router/src/router_factory.rs
279:    use crate::register_plugin;
316:    register_plugin!(
337:    register_plugin!(

We could restructure the tests so this isn't an issue, but...

I think it's better to have a unique name for the registration function.

**Comment by SimonSapin** [comment]
That’s what the `const _: () = {…};` part is for. Each `register` function would be in its own scope.

**Comment by garypen** [comment]
> That’s what the `const _: () = {…};` part is for. Each `register` function would be in its own scope.

Ah, I missed that. Let me try it...

**Review by bnjjj — APPROVED** [review]

**Pull request merged**
