### PR TITLE
Fix chunk formatting in multipart protocol

### LINKED ISSUE #4634: Router (1.38.0) emitting a last {"payload":null} message to the client before completing Subscription
Customer is facing an issue when their subgraph (DGS) sends a subscription complete message. They observe Apollo Router (1.38.0) sometimes emits a last {"payload":null} message to the client before completing the subscription.
When this null payload is emitted, Apollo Client throws an error.

**Example: frames from start to complete, when null payload is emitted**

```
--graphql
content-type: application/json

{}
--graphql
content-type: application/json

{"payload":{"data":{"toolingPing":"Pong -> 1"}}}
--graphql
content-type: application/json

{"payload":null}
--graphql--`

**Example: frames from start to complete, when null payload is not emitted**
`--graphql
content-type: application/json

{}
--graphql
content-type: application/json

{"payload":{"data":{"toolingPing":"Pong -> 1"}}}
--graphql--
```

**For Router, they are using v1.38.0.**

**They are also on Apollo Client 3.8.10.**

### PR DESCRIPTION
**Pull request by bnjjj**
This PR changes the way we're sending chunks in the stream. Instead of finishing the chunk with `\r\n` we don't send this at the end of our current chunk but instead at the beginning of the next one. For the end users nothing changes but it let us to close the stream with the right final boundary by appending `--\r\n` directly to the last chunk.

Fixes #4634

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by calvincestari** [comment]
Is it correct to assume that this change will affect the `@defer` messages too since they are also multipart protocol messages?

**Comment by bnjjj** [comment]
@calvincestari yes

**Review by alessbell — APPROVED** [review]
Tested with Apollo Client (both defer and multipart subscriptions over HTTP), lgtm.

**Review by calvincestari — APPROVED** [review]
I've got a local router running on this branch and Apollo iOS looks all good, receiving HTTP subscription messages as expected.

**Review by martinbonnin — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]

**Review by Geal — APPROVED** [review]

**Pull request merged**
