### PR TITLE
Cleanup unused bypass QP functionality

### PR DESCRIPTION
**Pull request by dariuszkuc**
Cleanup query planner code by removing unused bypass QP functionality. This was a gateway only feature that was never supported on the router.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Review by duckki — APPROVED** [review]
Looks good!

**Comment by dariuszkuc** [comment]
Looks like this one also impacts the QP redis cache tests -> I'll wait for the https://github.com/apollographql/router/pull/6354 before fixing this

**Comment by goto-bus-stop** [comment]
Love to see it, thanks for doing that 😁

**Comment by lrlna** [comment]
> Looks like this one also impacts the QP redis cache tests -> I'll wait for the https://github.com/apollographql/router/pull/6354 before fixing this

Yea, QueryPlannerConfig is part of the cache key (which is generally good, but bad for when we change the config)

**Comment by dariuszkuc** [comment]
@lrlna @SimonSapin am I missing something around redis cache key tests? I'd expect that this change should have also affected the `query_planner_redis_update_reuse_query_fragments` test but it seems like it didn't update the cache key? Just want to double check whether it is expected -> I'm guessing it didn't change the expected cache key there as in order to reuse fragments we have to explicitly switch back to the legacy QP and this config change only affects the native QP.

**Comment by lrlna** [comment]
we talked about this in a huddle, but for historical sake and anyone observing from a distance:

* `query_planner_redis_update_reuse_query_fragments` did not need its cache keys changed
   * it's using the legacy query planner explicitly with the legacy query planner's config
   * legacy query planner config was not affected as part of these changes

**Pull request merged**
