### PR TITLE
feat(xtask): add a shorthand to profile the planner

### PR DESCRIPTION
**Pull request by goto-bus-stop**
We are working through some known-slow operations in the native query planner, and this is a really useful way to generate a flame graph quickly and investigate specific queries.

```
cargo xtask fed-flame plan /path/to/query.graphql /path/to/supergraph.graphql
```

This compiles the apollo-federation CLI in release mode with debug info enabled, and then runs it with [samply], to produce a call tree and a flame graph. It can even show you exactly where in the code all the callsites are.

image

[samply]: https://github.com/mstange/samply

### CODE REVIEW

**Review by lrlna — CHANGES_REQUESTED** [review]
Can you add a small blurb to the `xtask` readme and the `DEVELOPMENT.md` file on running this?

**Comment by goto-bus-stop** [comment]
I was going to update the document in confluence instead of adding it here. fwiw the xtask readme.md is quite outdated and references commands that no longer exist 💀

**Comment by goto-bus-stop** [comment]
updated the readme to list the xtasks that i use regularly 😄

**Review by lrlna — APPROVED** [review]
Thank you!!

**Comment by goto-bus-stop** [comment]
Hmmm. I find that this hangs unexpectedly locally 🤔 
I would like to figure that out before I merge this and recommend people use it. It might be an issue with using `samply`.

**Comment by goto-bus-stop** [comment]
Okay, it was probably an issue with how I spawned the subprocess, I've switched to xshell which appears to do the right thing.

**Pull request merged**
