### PR TITLE
Enable JSON logs only if not a tty

### PR DESCRIPTION
**Pull request by cecton**
This will prevent JSON logs to be enabled when running inside a terminal.

Behavior:
- if running as a service of system.d for example => JSON logs
- if the stdout is redirected (`router | jq .`) => JSON logs
- on CI the stdout and stderr are often forced to TTY => normal logs (text with colors)

Why use `atty`?
- `isatty` is deprecated
- `console` is in our dev-dependencies so the license is not included

Related to #165 
Related to #46

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]
Super nice! :shipit:

**Review by o0Ignition0o — APPROVED** [review]

**Comment by cecton** [comment]
(merging this fast because it annoys me for developing)

**Comment by garypen** [comment]
I didn't get time to comment on this before it merged. The primary reason for defaulting to JSON logging is to provide JSON logs in production. I think this change will prevent us from generating JSON logs when running in kubernetes, which I think will, at some point, be the main production deployment environment for the router.

**Comment by abernix** [comment]
It wouldn't be difficult to convince me that we'd want CI use non-JSON and similarly feel that it'd be frustrating to have JSON output when merely running the router oneself!

Does K8s allocate/force a TTY? I could also believe that even in several environments where a TTY is **not** allocated (Docker might behave this way?) it might be less user-friendly to start with machine-readable JSON log output.

It's _possible_ that we just need to adopt an approach where those who **want** JSON logs ask for it explicitly, or we use different context clues other than TTY assignment to inform our decision (e.g., Kubernetes environment variables, perhaps? Maybe `KUBERNETES_SERVICE_HOST`?) if we're trying to optimize for doing the right thing in particular deployment environments like Kubernetes.

**Comment by Geal** [comment]
@cecton could you add a sentence describing this behaviour in the docs?

**Comment by cecton** [comment]
> I think this change will prevent us from generating JSON logs when running in kubernetes, which I think will, at some point, be the main production deployment environment for the router.

k8s doesn't seem to allocate a terminal by default so you will still get json logs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/

> It's possible that we just need to adopt an approach where those who want JSON logs ask for it explicitly

This approach is more reasonable to me than the other way around.

> @cecton could you add a sentence describing this behaviour in the docs?

@Geal sure

**Pull request merged**
