### PR TITLE
support duplicate selections

### LINKED ISSUE #568: an operation applied multiple times should be merged
found by fuzzing #528 with #566

an operation used multiple times should see its fields merged in the same object. If the operation is called with different sets of arguments, should it be merged?

```
====DOCUMENT===
query {
  me {
    id
    id
  }
  me {
    id
    name
  }
}


====GATEWAY====
Response { label: None, data: Object({"me": Object({"id": String("1"), "name": String("Ada Lovelace")})}), path: None, has_next: None, errors: [], extensions: {} }

====ROUTER====
Response { label: None, data: Object({"me": Object({"id": String("1")})}), path: None, has_next: None, errors: [], extensions: {} }
```

### PR DESCRIPTION
**Pull request by Geal**
Fix #568 

we can have multiple sub selections of a same fields coming from
multiple path (by merging operations, or using fragments), so we cannot
remove the field value to avoid a copy. Instead we should keep it in
place and copy whatever we need. This will result in a lot of copies,
but hopefully the ByteString type will reduce their impact

### CODE REVIEW

**Comment by Geal** [comment]
28% perf loss on this PR :(

**Comment by Geal** [comment]
perf test please

**Comment by Geal** [comment]
perf test please

**Comment by Geal** [comment]
perf tests are not working currently, so I don't know for the latest commits, but [0dc6ab9](https://github.com/apollographql/router/pull/574/commits/0dc6ab9b657088da08a1256348dad060a2a41dc4) was back to 5% from main: https://github.com/apollographql/router/runs/5409639824

So this PR is fine now (following commits were cleaning, bugfix and simplification outside of the hot path)

**Comment by Geal** [comment]
perf test please

**Comment by Geal** [comment]
the fuzzer has been running for 2 hours on this PR without finding an issue, I have good hopes now :)

**Review by BrynCooke — APPROVED** [review]
I tried following this code as best I could, it looks correct as far as I can tell.

**Pull request merged**
