### PR TITLE
Rename config files to match agreed suffix

### PR DESCRIPTION
**Pull request by BrynCooke**
Config file renames in example directory
`*.router.yaml`

### CODE REVIEW

**Review by garypen — CHANGES_REQUESTED** [review]
Would these be better named as: example.router.yaml ? For example, the unix_socket yaml doesn't have config in the name and I feel like we want to enable the `dev.router.yaml` and `prod.router.yaml` kind of template.

**Comment by abernix** [comment]
I agree with the line of thinking and consideration about it, @garypen.  I might even say that folks will typically put  `router.*.yaml` rather than `*.router.yaml` because its nice to have `router` files sorted together.  Of course this is just agreeing to a docs pattern that we like for the most part, and secondarily a pattern that will probably propagate out.

I think we should still be open to changes but I'd say we stay on `config.router.yaml` for the moment and then lift-and-shift all at once when we have a bit more time to have a conversation. (Read: land this PR)

**Review by abernix — APPROVED** [review]

**Comment by BrynCooke** [comment]
Uuugh, I saw the slack conversation first.
It's now `example.router.yaml`. I guess no more consistent/inconsistent.
We can still have the conversation and change later.

**Comment by abernix** [comment]
:shipit:

**Review by garypen — APPROVED** [review]

**Pull request merged**
