### PR TITLE
feat(plugin): add access to global configuration in plugins 

### PR DESCRIPTION
**Pull request by bnjjj**
Add ability to access to the global router data from a plugin.

### CODE REVIEW

**Review by garypen — COMMENTED** [review]
A general design question: do most plugins require access to the full config?

What I mean is: it's a bit ugly to pass two configs when we are creating plugin instances through the instance factory and I don't think most plugins need the full config.

What if, instead of "pushing" it to plugins, we added a function that allowed a plugin to access the full config if they needed to? Would that "look" better?

**Comment by bnjjj** [comment]
It could make sense. It's more visible to have it directly in the `PluginInit` but it could also be part of a helper function to get it. Are you thinking about having a global variable with global configuration inside ? Or something else ?
cc @garypen

**Comment by garypen** [comment]
> It could make sense. It's more visible to have it directly in the `PluginInit` but it could also be part of a helper function to get it. Are you thinking about having a global variable with global configuration inside ? Or something else ? cc @garypen

I think it's already held "globally" somewhere, so yes it would just be a function you call to get read only access to it.

**Comment by Geal** [comment]
the configuration is not global, plugin instances are linked to a specific configuration instance. If there's a global function to get the configuration, we can get in the case where a plugin created from an ancient version of the configuration, still in use for an in flight request, now switches to the new configuration. It sounds safer to pass it at the plugin creation

**Review by Geal — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]

**Comment by abernix** [comment]
@bnjjj What are next steps here?

**Comment by bnjjj** [comment]
Discuss with the team next week

**Comment by abernix** [comment]
We can easily re-open this and restore the branch, if we find we need it in the future, but at this point I think this has been open for a bit too long.

**Pull request closed without merging**
