### PR TITLE
prefix the prometheus metrics with apollo_router #1915

### LINKED ISSUE #1915: prometheus metric prefix for the router
I noticed in the grafana metric explorer, that most of the metrics available are prefixed with a name representing the executable/service. For example:
```
jaeger_http_<blah...>
kubelet_http_<blah...>
alertmanager_http_<blah...>
```
The router doesn't do this. router metrics look like:
```
http_<blah...>
```
Now, it's possible (after choosing a metric) to narrow down the search by other labels (such as `service` or `container`), so it's definitely possible to find the required `router` metrics but I wonder if we should adopt this prefix naming convention?

### PR DESCRIPTION
**Pull request by bnjjj**
close #1915

### CODE REVIEW

**Review by garypen — APPROVED** [review]

**Comment by BrynCooke** [comment]
SGTM

**Review by BrynCooke — APPROVED** [review]

**Comment by abernix** [comment]
So if we think about what Apollo Server would do here with this guidance, would we have chosen `server_`?   That ends up being a bit too generic.

I feel like it would be more than within our right to choose `apollo_` as the namespace prefix here and then still add `router_` after that — in the spirit of, "Apollo things will be in the `apollo_` namespace, and beyond that they will have granularity that is defined per-product

**Comment by abernix** [comment]
This seems like it should have come with documentation changes, too?: https://github.com/apollographql/router/blob/d62a0285aee37912c16c10794fb95b183b233898/docs/source/configuration/metrics.mdx

**Comment by garypen** [comment]
We can still fix this (i.e.: we haven't released since this change). guidance says "should" for 1 word restriction. I think there is a reasonable case for using 2. i.e.: let's go back to `apollo_router`.

**Comment by bnjjj** [comment]
Ok, will update the docs too! Good catch

**Pull request merged**
