### PR TITLE
deps: Use nu-ansi-term to replace unmaintained ansi_term

### PR DESCRIPTION
**Pull request by yanns**
Partially fixes https://rustsec.org/advisories/RUSTSEC-2021-0139

`clap` is still depending on [ansi_term](https://github.com/ogham/rust-ansi-term).

cargo audit before the change:
```
Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
├── clap 2.34.0
│   ├── structopt 0.3.26
│   │   └── cargo-scaffold 0.8.7
│   │       └── apollo-router-scaffold 1.12.1
│   └── cargo-scaffold 0.8.7
└── apollo-router 1.12.1
    ├── throw-error 0.1.0
    ├── supergraph_sdl 0.1.0
    ├── rhai-surrogate-cache-key 0.1.0
    ├── rhai-subgraph-request-log 0.1.0
    ├── rhai-logging 0.1.0
    ├── rhai-error-response-mutate 0.1.0
    ├── rhai-data-response-mutate 0.1.0
    ├── propagate-status-code 0.1.0
    ├── op-name-to-header 0.1.0
    ├── jwt-claims 0.1.0
    ├── hello-world 0.1.0
    ├── forbid_anonymous_operations_rhai 0.1.0
    ├── forbid-anonymous-operations 0.1.0
    ├── external-subgraph 0.1.0
    ├── cookies-to-headers 0.1.0
    ├── context-data 0.1.0
    ├── async-allow-client-id 0.1.0
    ├── apollo-router-benchmarks 1.12.1
    └── add-timestamp-header 0.1.0
```

cargo audit after the change:
```
Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
└── clap 2.34.0
    ├── structopt 0.3.26
    │   └── cargo-scaffold 0.8.7
    │       └── apollo-router-scaffold 1.12.1
    └── cargo-scaffold 0.8.7
```

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]
Sorry for the delay @yanns, could you rebase on dev and merge conflict in order to merge it please ?

**Comment by yanns** [comment]
> Sorry for the delay @yanns, could you rebase on dev and merge conflict in order to merge it please ?

done

**Comment by yanns** [comment]
I'll fix the tests

**Comment by yanns** [comment]
the project is compiling again. Ready to review.

**Pull request merged**
