### PR TITLE
Add dotenv to allow router to read environment variables from .env file

### PR DESCRIPTION
**Pull request by andrewmcgivery**
Add dotenv to allow router to read environment variables from .env file

Possibly worth discussing:

- This is currently implemented to be "on by default". Reason I didn't put this behind a config or option flag is because at that point, it is too late since the options parse environment values. Possible workaround is to do a more "manual" read of the argument separate from the normal parsing code specifically for this flag.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Review by goto-bus-stop — COMMENTED** [review]
If we do this we should use the `dotenvy` crate, as `dotenv` is unmaintained.

**Comment by andrewmcgivery** [comment]
> If we do this we should use the `dotenvy` crate, as `dotenv` is unmaintained.

Good catch. Switched to that package!

**Review by bnjjj — COMMENTED** [review]
The overall PR LGTM, I would really have this feature in the router because I already struggled with that. I'm just wondering what could be the impact on our existing users ? Could it break something or have weird behavior ? Like for example what if they already had that .env file with wrong values but they're still providing environment variables like they always did before with the right values ? What's the priority order in that case ? Also does it keep the same logics if they use the argument in command line (like `--config` for example) but they're also providing the `APOLLO_ROUTER_CONFIG_PATH` ? And what's the behavior now if additionally we provide the same env var in .env file ? I think we need to test it manually (at least) and document it somewhere

**Comment by abernix** [comment]
Also plenty of folks use `direnv` or _many other_ tools (including Docker itself) that handles this in their local environment and additionally automatically uses different `.env` files for different environments.

I'm really not sure that the Router should really take on this concern when there are off the shelf tools that handle this generically.  I'd like to know why those other tools can't just be used without introducing this to the Router directly, before we entertain a PR that adds it.

**Pull request closed without merging**
