### PR TITLE
Show cookie toggle for embedded sandbox

### PR DESCRIPTION
**Pull request by esilverm**
**Description**

[JIRA](https://apollographql.atlassian.net/browse/NEBULA-2011)
[Related Embedded Explorer PR](https://github.com/apollographql/embeddable-explorer/pull/215)

Rover's embedded sandbox should let users toggle their includeCookies option in embedded Sandbox. This adjusts the config for embedded sandbox to let users do this.

NOTE: This PR requires a new release of our embedded explorer packages to be merged. For now I will leave it as a draft until the PR above has been approved and merged and a new version has been released

### CODE REVIEW

**Comment by esilverm** [comment]
@mayakoneval

**Review by bnjjj — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]
LGTM! Flagging @abernix just in case

**Review by abernix — APPROVED** [review]
LGTM

**Review by abernix — APPROVED** [review]
This seems like it needs a changelog entry which is currently missing.  [The guide is here](https://github.com/apollographql/router/blob/dev/.changesets/README.md#how-to-create-a-changelog-entry) for that.  Feel free to merge whenever you're done with this PR, though!

**Comment by esilverm** [comment]
@abernix @o0Ignition0o @bnjjj Thank you for the reviews!! I don't have write access to this repo so I cannot merge my changes, but I went in and added a changeset so it should be all good to merge when any of you have the chance.

**Comment by abernix** [comment]
Auto-merge enabled!

**Pull request merged**
