### PR TITLE
helm chart: Rhai + istio support

### PR DESCRIPTION
**Pull request by o0Ignition0o**
helm chart: add rhai script support, and istio virtualservice + egress rules
Bump the chart version, and propagate the given fullName as a default `service.name`

### CODE REVIEW

**Review by garypen — COMMENTED** [review]
Looks good. Just needs a change log, I think...

**Comment by o0Ignition0o** [comment]
Going to backport the work we just did on the service.name, add a changelog and we should be set!

**Review by garypen — APPROVED** [review]
Nice work. I think this is a really nice addition to our helm capabilities.

**Review by garypen — CHANGES_REQUESTED** [review]
Just remembered. The chart version must be incremented.

**Review by garypen — APPROVED** [review]

**Pull request merged**
