### PR TITLE
typo in ensure_expected_type_kind

### PR DESCRIPTION
**Pull request by lennyburdette**
am i reading this right?

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Review by SimonSapin — APPROVED** [review]
Yes, I double checked with `function ensureSameTypeKind(` in `internals-js/src/directiveAndTypeSpecification.ts`

**Comment by SimonSapin** [comment]
It’s a bit worrying that no test is affected by this but we still have plenty of tests left to port

**Comment by duckki** [comment]
Nice catch!
This part of code will only be exercised by composition, which we don't use yet.

**Review by duckki — APPROVED** [review]

**Comment by lennyburdette** [comment]
yeah i caught this when hacking with extract_subgraphs_from_supergraph

**Comment by duckki** [comment]
Please go ahead and merge it.

**Pull request merged**
