### PR TITLE
docs: updates some readme wording

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
This PR updates some wording in the router docs. Some of these changes y'all may not want to make, but I think most of them are helpful changes.

### CODE REVIEW

**Comment by EverlastingBugstopper** [comment]
do we need a changelog entry for this? methinks not but i'm not sure how y'all do things over in these here parts

**Comment by o0Ignition0o** [comment]
We tend to add an entry, which allows your nickname to show up in the release notes :D I'd put it in the docs, or maybe the chore section if you feel like writing an entry!

**Review by garypen — APPROVED** [review]
Thanks @EverlastingBugstopper !

**Review by abernix — APPROVED** [review]
Thank you so much for this! LGTM, @EverlastingBugstopper . :shipit:

**Pull request merged**
