### PR TITLE
feat: enable both_best_effort query planners

### PR DESCRIPTION
**Pull request by lrlna**
Formally switches `#[default]` to `both_best_effort` for `experimental_query_planner_mode` and adds a changelog entry.

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]

**Review by chandrikas — APPROVED** [review]
Looks good as is. However, I was wondering if we could have a "learn more" link. As a user when I read this, my first thought is - "It can't be for free. What's the impact? They say it's not in the hot path but what do I need to know before I decide I should leave this on or off"

**Comment by lrlna** [comment]
@chandrikas do you mean having a docs page for this as well?

**Comment by chandrikas** [comment]
Can we have a hidden docs page for now that can be removed later?

**Comment by lrlna** [comment]
@chandrikas I'll talk to the docs team about it! I am going to merge this in, and we can edit the changelog in the release prep PR. I need to try to get an rc out with the code change today 🙏

**Pull request merged**
