### PR TITLE
ci: common env variables in config as `common_job_environment` alias.

### PR DESCRIPTION
**Pull request by abernix**
Previously, the `CARGO_NET_GIT_FETCH_WITH_CLI` variable was defined in our "Secrets" within the CircleCI user interface.  Practically speaking, that would be okay but moving it into this file allows us to not pass secrets to PR CI runs while still enabling this important Cargo configuration.  Doing this also allows this to work seamlessly if someone were to want to run CI on their own CircleCI on their own fork _without_ a PR to our repo.

This introduces an anchor and alias that let us keep that DRY throughout.  While I'm at it, I've also moved NODE_VERSION and NPM_VERSION to the new `common_job_environment`.  While this does add it to one job where it was not present before, that should be a no-op (though conceivably desirable, if it were ever _not_ a no-op!).

After merging this, we should remove `CARGO_NET_GIT_FETCH_WITH_CLI` from [the config](https://app.circleci.com/settings/project/github/apollographql/router/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fapollographql%2Frouter) and enable CI for PRs from forks _without_ secrets.

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
A [.cargo/Config.toml file](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format) should work and remove the need for this env variable alltogether (which would play nicer with users who fork and try to run it locally):

```toml
[net]
git-fetch-with-cli = true   # use the `git` executable for git operations
```

**Comment by abernix** [comment]
@o0Ignition0o While I agree that it could be done in that way, this didn't strike me as a configuration that we want/need everyone to adopt (in fact, this could even make things _worse_ for some users).   I'd claim this is really a CircleCI-specific desire, probably motivated partially by things like https://github.com/rust-lang/cargo/issues/10280.  By doing it as an environment variable, we ensure that it works equally for all `cargo` commands since it's set at the container level, and it's also just easier than writing out this file into CI.

**Comment by o0Ignition0o** [comment]
I see, this sounds good to me then!

**Review by o0Ignition0o — APPROVED** [review]

**Comment by abernix** [comment]
> After merging this, we should remove `CARGO_NET_GIT_FETCH_WITH_CLI` from [the config](https://app.circleci.com/settings/project/github/apollographql/router/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fapollographql%2Frouter) and enable CI for PRs from forks _without_ secrets.

I've officially done this now and deleted it from the CircleCI project settings.

**Pull request merged**
