### PR TITLE
run federation 2 demo

### LINKED ISSUE #646: example: OTEL / custom telemetry using YAML

### PR DESCRIPTION
**Pull request by Geal**
Fix #646 

starting the containers:

docker-compose -f docker-compose-federation2.yml up

starting the router:

cargo run -- -s examples/graphql/federation2.graphql -c examples/telemetry/otlp.router.yaml

The Zipkin server collecting traces will be available at
http://127.0.0.1:9411/zipkin/

### CODE REVIEW

**Comment by abernix** [comment]
I'm linking this to https://github.com/apollographql/router/issues/643, but please remove that if that's not the intention. ;)

**Comment by Geal** [comment]
this is more to make the fed2 demo available for local tests, I have not run the entire test suite, I'll try that tomorrow instead

**Comment by Geal** [comment]
so far fed2 seems to be working with the router, and now the opentelemetry headers are sent properly, so if I don't see the subgraph spans in zipkin, it's mainly a configuration issue, but that should not block this PR

**Review by BrynCooke — APPROVED** [review]

**Comment by Geal** [comment]
ok, this is now working properly!

**Pull request merged**
