### PR TITLE
add additional treatment indicating JWT is experimental

### PR DESCRIPTION
**Pull request by garypen**
* Move the changelog from feature to experimental.
* Corrects changelog example lacking `experimental` nesting.
* Adds the [GitHub Discussion](https://github.com/apollographql/router/discussions/2391) to the list of experimental features for console output.

### CODE REVIEW

**Review by abernix — APPROVED** [review]

**Comment by SimonSapin** [comment]
Should it also be visibly experimental without reading the changelog? Such as calling the config section `experimental_jwt` instead of `jwt`

**Comment by SimonSapin** [comment]
(I think we already discussed multiple times how to mark things experimental in general but I don’t remember the latest conclusions)

**Review by abernix — CHANGES_REQUESTED** [review]
Agree with @SimonSapin's comment https://github.com/apollographql/router/pull/2427#issuecomment-1396652543 (Changing my Approval to Request changes):

> Should it also be visibly experimental without reading the changelog? Such as calling the config section `experimental_jwt` instead of `jwt`

Yes — this is critical.  It should have that prefix and the other experimental treatments on it.

**Comment by garypen** [comment]
It was a mistake in the example configuration that I should have updated. I've updated the configuration to the correct syntax now, which includes the `experimental` section.

**Comment by abernix** [comment]
@garypen Cool! Should this also have the [Experimental discussion](https://github.com/apollographql/router/discussions/2391) that you created added to the `experimental_features.json` for the log output around experimental features to produce the appropriate links?  Like these:

https://github.com/apollographql/router/blob/179a746aa9417b0f40a55c5413f2a071b30fc86c/apollo-router/experimental_features.json#L1-L5

**Comment by garypen** [comment]
> router/apollo-router/experimental_features.json

it should... I'll do it now.

**Review by abernix — APPROVED** [review]
I edited the PR title and body to reflect the new scope and LGTM!

**Pull request merged**
