### PR TITLE
Get variable default values from the query for query plan condition nodes

### LINKED ISSUE #1603: query plan condition nodes do not use default values of variables
Blocked on https://github.com/apollographql/federation/issues/2100

Example query:

```graphql
query X($if: Boolean! = true) {
    ... @defer(if: $if) {
        x
    }
}
```

relevant code:

https://github.com/apollographql/router/blob/5cb00657ae71d6f502913b3ff912591e64355a4b/apollo-router/src/query_planner/mod.rs#L610-L623

### PR DESCRIPTION
**Pull request by Geal**
Fix #1603
~Blocked on https://github.com/apollographql/federation/issues/2100~
~Blocked on https://github.com/apollographql/federation/pull/2121~
~Blocked on #1672~
~(can't test until that PR is fixed)~ tested, it works

### CODE REVIEW

**Comment by abernix** [comment]
#1666 now tracks 2.1.1  and https://github.com/apollographql/federation-rs/pull/164 is a step in the right direction)

**Review by garypen — APPROVED** [review]

**Comment by Geal** [comment]
once #1672 is merged I'll be able to test that one

**Comment by Geal** [comment]
Now that I added a test, I get this error :thinking: :
```json
{
  "errors": [
    {
      "message": "invalid type for variable: 'if'",
      "locations": [],
      "path": null,
      "extensions": {
        "type": "ValidationInvalidTypeVariable",
        "name": "if"
      }
    }
  ]
}
```

**Comment by abernix** [comment]
As I noted in the linked issue, all of the blockers above should be *in* the Router proper now.

**Comment by abernix** [comment]
I believe I've fixed merge conflicts.

**Review by bnjjj — APPROVED** [review]

**Comment by Geal** [comment]
so the invalid type for `$if` is still there: https://github.com/apollographql/router/pull/1640/commits/30f39cf988a50d2a2e324459f87bc943def52ea2 

this feels weird because in the test, it is a `Boolean!`: https://github.com/apollographql/router/pull/1640/files#diff-0654669b073b6481f538035cfdc0ad46b209207837121627f534ec8c90fa1432R692 and in the spec too: https://github.com/graphql/graphql-spec/pull/742/files#diff-30a69c5a5eded8e1aea52e53dad1181e6ec8f549ca2c50570b035153e2de1c43R2128

**Comment by Geal** [comment]
@abernix were the blocking issues fixed in the router-bridge release currently used on router main?

**Comment by Geal** [comment]
ok it's coming from the router's variable validation

**Comment by abernix** [comment]
> @abernix were the blocking issues fixed in the router-bridge release currently used on router main?

Yup, they were.  Seems like you found what I eventually found but didn't have a chance to dig into.  Thanks! 😄

**Comment by Geal** [comment]
I'm re-requesting reviews because there's an additional fix for default variable value validation

**Review by bnjjj — APPROVED** [review]

**Pull request merged**
