### PR TITLE
support query plans with empty primary subselections

### LINKED ISSUE #1800: Error when deferring fragments on the top level Query field
**Describe the bug**
Per the `graphql` [test suite](https://github.com/graphql/graphql-js/blob/a24a9f35b876bdd0d5050eca34d3020bd0db9a29/src/execution/__tests__/defer-test.ts#L196), which we're using to guide E2E testing with Apollo Client, we have a test that attempts to defer a fragment on the top level Query field when running the [supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2):

The following query:

```graphql
  query TestQuery {
    ...QueryFragment @defer
  }
  fragment QueryFragment on Query {
    allProducts {
      dimensions {
        size
      }
      variation {
        id
        name
      }
      sku
      id
    }
  }
```

Produces the error:

```
{
    "errors": [
        {
            "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `13645066633052847595`: `deno: couldn't deserialize response : `Error(\"missing field `subselection`\", line: 0, column: 0)``.`",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

**To Reproduce**
1. Clone https://github.com/alessbell/router-defer-e2e-tests
2. Bring up the `supergraph-demo-fed2` router running on port 4000
3. In `router-defer-e2e-tests`: `cd CRA-demo && npm i && npm start`
4. Visit `http://localhost:3000/defer-top-level-query-field`

**Expected behavior**
The query to not return an internal server error.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version: 12.5

### PR DESCRIPTION
**Pull request by Geal**
Fix #1800

in a query like this:

```graphql
query {
  me {
    reviews {
      product {
        ... on Product @defer(label: "A") {
          name

          ... on Product @defer(label: "B") {
            price
          }
        }
      }
    }
  }
}
```

The primary response would not contain any data, as it would only be filled out by deferred responses.
With this commit, the router will return the following:

```
--graphql
content-type: application/json

{"data":{"me":{"reviews":[{"product":{"name":null,"price":null}},{"product":{"name":null,"price":null}}]}},"hasNext":true}
--graphql
content-type: application/json

{"hasNext":true,"incremental":[{"label":"A","data":{"name":"Table"},"path":["me","reviews",0,"product"]},{"label":"A","data":{"name":"Couch"},"path":["me","reviews",1,"product"]}]}
--graphql
content-type: application/json

{"hasNext":false,"incremental":[{"label":"B","data":{"price":899},"path":["me","reviews",0,"product"]},{"label":"B","data":{"price":1299},"path":["me","reviews",1,"product"]}]}
--graphql--

```

TODO:
- [x] properly recognize that a query is deferred instead of guessing it from what query plan execution returns https://github.com/apollographql/router/pull/1778/commits/7504d83a8cc60cae1dc2f3268cf873c43330a9c2
- [x] properly change to response formatting's behaviour when acting on primary or deferred responses https://github.com/apollographql/router/pull/1778/commits/4d6dce84ae23a73dd83ce7b635664508ab47b27f
- [x] refactoring tests in `spec/query.rs` to allow modifications to response formatting  https://github.com/apollographql/router/pull/1798

### CODE REVIEW

**Review by o0Ignition0o — APPROVED** [review]

**Review by bnjjj — APPROVED** [review]

**Review by garypen — APPROVED** [review]

**Comment by Geal** [comment]
(force pushed because I messed up my merge)

**Comment by abernix** [comment]
@Geal looks like this just needs an `insta review` to get tests fixed?

**Comment by Geal** [comment]
no, it should not be affecting that test

**Comment by Geal** [comment]
here's what happens. If I use this query:

```graphql
query X($if: Boolean! = true) {
    me {
        id
        ...@defer(label: "name", if: $if) {
            name
        }
    }
}
```

the router's code detects it as a query with `@defer`, and so will try to apply the specific formatting behaviour, ie looking at the response's subselection field, that indicates the shape of each response. But the generated query plan here is a condition node with on one side, subselections `{ me { id } }` then `{ me { name } }`, and on the other side the query `{ me { id name } }` but without a subselection node, so with my previous fix, that was interpreted as an empty primary query, so the data is replaced with an empty object.

To fix this, I think I need to make the code that detects deferred queries a bit smarter, so it could interpret variables as well

**Comment by Geal** [comment]
ok this should work properly now, it can be reviewed again

**Review by bnjjj — APPROVED** [review]

**Pull request merged**
