### PR TITLE
another dedup improvement

### PR DESCRIPTION
**Pull request by garypen**
Try to close the loop even tighter around potential race condition failures.

Because there is a (potentially large) period of time between subscribing to a sender and actually waiting to `recv()`, the sender may go away. That's difficult to control under a lock, because we can't wait under the lock or that will cause a deadlock.

Luckily, we can rely on the fact that when a sender goes away, the value it retrieved is in the cache. It might not be, of course, so we might still have a failure here and carefully account for that case.

### CODE REVIEW

**Comment by Geal** [comment]
this does not look like the behaviour described in the broadcast receiver. From https://docs.rs/tokio/latest/tokio/sync/broadcast/struct.Receiver.html#method.recv :
>Each [Receiver](https://docs.rs/tokio/latest/tokio/sync/broadcast/struct.Receiver.html) handle will receive a clone of all values sent **after** it has subscribed.

So if the sender has gone away when we call recv() and we get a `Closed` message, that means the sender has not sent anything after we subscribed

**Review by bnjjj — APPROVED** [review]

**Comment by garypen** [comment]
> https://docs.rs/tokio/latest/tokio/sync/broadcast/struct.Receiver.html#method.recv

I read that through several times and it seems ambiguous to me. I can certainly interpret that as meaning: you will get copies unless the sender closes...
However, I'll re-examine the logic flow and see if I can better understand what is happening here. I'll create a test scenario that exercises the logic path we think might be problematic.

**Review by o0Ignition0o — APPROVED** [review]
The discussion seems a bit stale over here, I'm aproving this hoping this will drive either a merge or a close forward :D

**Comment by abernix** [comment]
@garypen Next steps on this PR?

**Pull request closed without merging**
