### PR TITLE
Variable deduplication in query planner

### LINKED ISSUE #87: variable deduplication
When doing a query like this:

```graphql
query ExampleQuery($topProductsFirst: Int) {
  topProducts(first: $topProductsFirst) {
    name
   reviews {
    body author {
      username
      reviews {
        id
        body
        product {
          name
        }
      }
    }
  }
}
```

we will do a serie of requests, first to producs to get the topproducts, then to reviews, then to products. The second request to products aggregates the queries but does not deduplicate them, so we get variables like this:

```
{"representations":
  Array([
    Object({"__typename": String("Product"), "upc": String("1")}),
    Object({"__typename": String("Product"), "upc": String("2")}),
    Object({"__typename": String("Product"), "upc": String("3")}),  
    Object({"__typename": String("Product"), "upc": String("1")}), 
    Object({"__typename": String("Product"), "upc": String("1")}),
    Object({"__typename": String("Product"), "upc": String("2")}), 
    Object({"__typename": String("Product"), "upc": String("3")}),
    Object({"__typename": String("Product"), "upc": String("1")})
])}
```

The router should be able to recognize that we are asking multiple times for the same data, and only ask each item once, so there should be a mapping between the reviews and the products query: (with indexes, reviews should reference `[0, 1, 2, 0, 0, 1, 2, 0]` from the variables array `[ { "__typename": "Product", "upc": "1" },  { "__typename": "Product", "upc": "2" },  { "__typename": "Product", "upc": "3" } ]`)

To go further, the first request to products returned this:

```
Object({"topProducts":
  Array([
    Object({"__typename": String("Product"), "upc": String("1"), "name": String("Table")}),
    Object({"__typename": String("Product"), "upc": String("2"), "name": String("Couch")}),
    Object({"__typename": String("Product"), "upc": String("3"), "name": String("Chair")})])})
```

so for each of these products, we already knew the name, so we could have avoided entirely the second call to products.

## Implementation details

Variables in representations are generated here:

https://github.com/apollographql/router/blob/46b01911373cfeda7ca9408fd649447b352bb5bf/crates/apollo-router-core/src/federated.rs#L314-L315 from `select` in https://github.com/apollographql/router/blob/46b01911373cfeda7ca9408fd649447b352bb5bf/crates/apollo-router-core/src/response.rs#L59-L85

The annoying part is that since we are working with `serde_json::Value` elements, that do not implement `Hash`, they are hard to deduplicate (for now, there's work happening on that https://github.com/serde-rs/json/issues/747 https://github.com/serde-rs/json/issues/720 https://github.com/serde-rs/json/pull/814 )

What could be done here? Should we use another structure than `serde_json::Value`? Should the response contain a kind of repository of values to look up and avoid some queries?

### PR DESCRIPTION
**Pull request by bnjjj**
close #87 

Before this change we had this `__entities`:

```
entities.len() 8
entities [
    Object({
        "name": String(
            "Table",
        ),
    }),
    Object({
        "name": String(
            "Couch",
        ),
    }),
    Object({
        "name": String(
            "Chair",
        ),
    }),
    Object({
        "name": String(
            "Table",
        ),
    }),
    Object({
        "name": String(
            "Table",
        ),
    }),
    Object({
        "name": String(
            "Couch",
        ),
    }),
    Object({
        "name": String(
            "Chair",
        ),
    }),
    Object({
        "name": String(
            "Table",
        ),
    }),
]
```

Now we have:

```
entities len 3
entities [
    Object({
        "name": String(
            "Table",
        ),
    }),
    Object({
        "name": String(
            "Couch",
        ),
    }),
    Object({
        "name": String(
            "Chair",
        ),
    }),
]
```

in responses, but I also deduplicate in the requests so it's less traffic either on the request and the response.

### CODE REVIEW

**Comment by BrynCooke** [comment]
Let's not merge this before GA.

**Review by abernix — COMMENTED** [review]
I love this, with a timing catch. 😉 

As long as we're doing **deep comparisons** on the representations, this is safe and desirable.  This is also something that we've wanted to do for a very long time in the Gateway and something users have wanted!

With that in mind, my suggestion is that we either:

1. Punting this until after GA; **or**
2. Making this a configuration option that is **off** by default

I suspect my preference could be option 2.

My primary motivation for this suggestion is that I believe this could make it more challenging for adopters (e.g., SREs analyzing such a deployment) to accurately analyze the differences  in behavior between the Gateway and the Router, which we have tried to keep largely the same.  It would be easier if the shapes of the subgraph requests were as similar as possible — this might tie into whatever tool/diffs that come out of https://github.com/apollographql/router/issues/765 if someone was comparing Router vs Gateway.

As a secondary motivation, because this is an _optimization_ while we're in a push to GA (which I'd claim should primarily on _stabilizing_ what we have, rather than new features that differentiate things from the Gateway — even if desirable!).

There are, I think, a number of users who are interested in this that have probably opened issues on the `federation` repository that we might want to have try it out, so a configuration option could enable that.  It's also just a great fast-follow to GA.

My _one_ technical note on this PR is that I think it should introduce some tests, and _administratively_, looking for a `CHANGELOG.md`.

Thoughts?

**Comment by Geal** [comment]
Deep comparisons should not be a huge issue, as the Hash implementation does it. If there's a case where a representation is similar but does not hash the same way (example: fields in different order), it should be safe, because it would only result in more data requested.
I agree though, that needs more tests. But still, great work 😃

**Comment by bnjjj** [comment]
Discussed with @BrynCooke, let's merge it POST-GA

**Review by BrynCooke — CHANGES_REQUESTED** [review]
I still believe that this can be activated via the traffic shaping plugin. 

QueryPlannerRequest should have QueryPlanOptions as a field and the traffic shaping plugin should mutate the options to enable dedup.

**Comment by bnjjj** [comment]
Ok if we're ok to expose the queryplan options then indeed I think it could work

**Review by BrynCooke — APPROVED** [review]

**Pull request merged**
