### PR TITLE
Strip dashes from trace_id in CustomTraceIdPropagator

### LINKED ISSUE #4892: Header added to request in rhai does not propagated into logs trace_id field
**Describe the bug**

Router version: v1.43.1

I use rhai to insert a `x-trace-id` header into request. Then I expect value of this header to be a `trace_id` in logs.

**To Reproduce**

Here I use `x-trace-id` to propagate header value to logs.
If `x-trace-id` present in headers from browser request - it works fine. But if I add `x-trace-id` header in rhai script - value does not propagated.

```
telemetry:
  exporters:
    tracing:
      propagation:
        request:
          header_name: x-trace-id
    logging:
      stdout:
        enabled: true
        format:
           json:
             display_level: true
             display_timestamp: true
             display_trace_id: true
             display_span_id: true
```

rhai script

```
fn supergraph_service(service) {
    let adapt_request_id = |request| {
        if request.headers.contains("x-request-id") {
            // x_request_id is a uuid4
            let x_request_id = request.headers["x-request-id"];
            x_request_id.replace("-", "");
            print(`x-request-id: ${x_request_id}`);
           // x-trace-id is just a copy of x-request-id without dashes
           // so router can parse it properly
           // we then restore it to uuid format in the logs processor
           request.headers["x-trace-id"] = x_request_id;
       }
    };

    service.map_request(adapt_request_id);
}
```

**Expected behavior**

I expect that rhai-created header propagated to `trace_id` field in logs.

### PR DESCRIPTION
**Pull request by kindermax**
When trace_id taken from headers it can be a uuid4 with dashes and `opentelemetry::trace::TraceId::from_hex` will not parse this in proper `TraceId`

Fixes #4892

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

### CODE REVIEW

**Comment by BrynCooke** [comment]
@kindermax just pinging to remind you that we can't merge this until the CLA is signed: https://github.com/apollographql/router/pull/5071#issuecomment-2092983643
Otherwise it looks looks good to me.

**Comment by BrynCooke** [comment]
@kindermax Strange, usually the bot comes along with a comment to say that things are OK. I'll check if there's anything going on.

**Comment by kindermax** [comment]
@BrynCooke, is there anything I can do to help merge this PR ? Is see some failing `arm_linux_test` and `NEXT_CHANGELOG.md reminder` but I do not know what to do with it ?

**Comment by smyrick** [comment]
@kindermax You can create a change set to describe your feature for the changelog following the docs here: https://github.com/apollographql/router/tree/dev/.changesets

**Comment by BrynCooke** [comment]
Yeah I think we just need a changeset and then we're good to go.

**Comment by kindermax** [comment]
Changeset added.

**Comment by kindermax** [comment]
I see some failing tests but I'm not sure if it is related to this PR (but I could be wrong)

**Comment by BrynCooke** [comment]
@kindermax Yes there is something weird going on with router bridge and CI right now. Don't worry I'lll make sure we merge this before the next release of the router.

**Review by bnjjj — APPROVED** [review]

**Comment by kindermax** [comment]
Just wanted to say thank you since it is my first rust contribution, and you guys were very supportive. ❤️

**Pull request merged**
