### PR TITLE
xtask release process

### PR DESCRIPTION
**Pull request by Geal**
This is a xtask based release process, that follows the commands defined in our `RELEASE_CHECKLIST.md` file, storing the current state of the process in the file `.release-state.json`, and prompting the user regularly for new info.

This can be executed by running `cargo xtask release start`, then calling `cargo xtask release continue` at each step

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by Geal** [comment]
Raw output of this command that I'll put in RELEASE_CHECKLIST.md tomorrow:


# Using the new release automation

The release process precedently described can be executed through `cargo xtask` commands that store the required environment variables, along with the current state of the process, in a file called `.release-state.json`.
This can be executed by running cargo xtask release start, then calling cargo xtask release continue at each step.

## Starting the process

Run `cargo xtask release start` and it will prompt you for the version number you want, origin, github repository and the git ref to start from (branch, commit id or HEAD):

```
Starting release process
Version?: 1.123.456
Git origin?: origin
Github repository?: apollographql/router
Git ref?: HEAD
Setting up the repository
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
Already up to date.
fatal: A branch named '1.123.456' already exists.
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for '1.123.456' on GitHub by visiting:
remote:      https://github.com/apollographql/router/pull/new/1.123.456
remote: 
To github.com:apollographql/router.git
 * [new branch]          1.123.456 -> 1.123.456
Branch '1.123.456' set up to track remote branch '1.123.456' from 'origin'.
Creating the release PR
Warning: 34 uncommitted changes

Creating draft pull request for dev into main in apollographql/router

https://github.com/apollographql/router/pull/5519
Success!
```

CLI output has ANSI escapes to put emphasis on xtask messages VS underlying command output.

If you had already started a release, it will ask you if you want to start a new one:

```
Starting release process
A release state file already exists, do you want to remove it and start a new one? [y/N]
```

## Create a pre release PR

After the draft, continue the process with `cargo xtask release continue`:

```
Select next release step
Next step?:
> create a prerelease
  create the final release PR
```

Select `create a prerelease` in the choice:

```
Select next release step
Next step?: create a prerelease
Creating the pre release PR
prerelease suffix? 1.123.456-: rc.0
Switched to branch '1.123.456'
Your branch is up to date with 'origin/1.123.456'.
From github.com:apollographql/router
 * branch                1.123.456  -> FETCH_HEAD
Already up to date.
prerelease version:  1.123.456-rc.0
updating Cargo.toml files
    Upgraded apollo-federation from 1.49.1 to 1.123.456-rc.0
Updated dependency apollo-router from =1.49.1 to =1.123.456-rc.0
    Upgraded apollo-router from 1.49.1 to 1.123.456-rc.0
    Upgraded apollo-router-scaffold from 1.49.1 to 1.123.456-rc.0
    Upgraded apollo-router-benchmarks from 1.49.1 to 1.123.456-rc.0
replace in file: "./apollo-router-scaffold/templates/base/Cargo.template.toml"
replace in file: "./apollo-router-scaffold/templates/base/xtask/Cargo.template.toml"
updating lock file
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/geal/dev/router/apollo-router-scaffold/scaffold-test/Cargo.toml
workspace: /home/geal/dev/router/Cargo.toml
warning: /home/geal/dev/router/fuzz/Cargo.toml: version requirement `=0.5.27+v2.8.1` for dependency `router-bridge` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /home/geal/dev/router/apollo-router/Cargo.toml: version requirement `=0.5.27+v2.8.1` for dependency `router-bridge` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
    Blocking waiting for file lock on build directory
    Checking bytes v1.6.0
    Checking log v0.4.20
   Compiling syn v1.0.109
   Compiling generic-array v0.14.7
   Compiling serde v1.0.199
   [...]
       Checking opentelemetry-otlp v0.13.0
    Finished dev [unoptimized + debuginfo] target(s) in 59.12s
checking compliance
   Compiling xtask v1.5.0 (/home/geal/dev/router/xtask)
    Finished dev [unoptimized + debuginfo] target(s) in 1.51s
     Running `xtask/target/debug/xtask check-compliance`
advisories ok, bans ok, licenses ok, sources ok
Success!
updating install script
replace in file: "./scripts/install.sh"
updating helm charts
replace in file: "./helm/chart/router/Chart.yaml"
replace in file: "./helm/chart/router/Chart.yaml"
INFO[2024-06-24T19:09:51+02:00] Found Chart directories [router]             
INFO[2024-06-24T19:09:51+02:00] Generating README Documentation for chart router 
updating docs
replace in file: "./docs/source/containerization/docker.mdx"
replace in file: "./docs/source/containerization/kubernetes.mdx"
replace in file: "./docs/source/containerization/kubernetes.mdx"
updating docker files
replace in file: "./dockerfiles/tracing/docker-compose.zipkin.yml"
replace in file: "./dockerfiles/tracing/docker-compose.datadog.yml"
replace in file: "./dockerfiles/tracing/docker-compose.jaeger.yml"
please check the changes and add them with `git add -up .`
diff --git a/Cargo.lock b/Cargo.lock
index 85c09fe6f..73c01ec73 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -422,7 +422,7 @@ dependencies = [
 
 [[package]]
 name = "apollo-federation"
-version = "1.49.1"
+version = "1.123.456-rc.0"
 dependencies = [
  "apollo-compiler",
  "derive_more",
(1/4) Stage this hunk [y,n,q,a,d,j,J,g,/,e,?]? 
```

Now follow the `git add -up .` process. Then finish the prerelease PR.


```
Commit the changes and build the prerelease? yes
[1.123.456 a83fb721f] prep release: v1.123.456-rc.0
 13 files changed, 21 insertions(+), 21 deletions(-)
Enumerating objects: 54, done.
Counting objects: 100% (54/54), done.
Delta compression using up to 16 threads
Compressing objects: 100% (26/26), done.
Writing objects: 100% (28/28), 2.57 KiB | 2.57 MiB/s, done.
Total 28 (delta 19), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (19/19), completed with 19 local objects.
remote: Bypassed rule violations for refs/heads/1.123.456:
remote: 
remote: - Changes must be made through a pull request.
remote: 
remote: - 7 of 7 required status checks are expected.
remote: 
remote: 
remote: GitHub found 12 vulnerabilities on apollographql/router's default branch (7 high, 4 moderate, 1 low). To find out more, visit:
remote:      https://github.com/apollographql/router/security/dependabot
remote: 
To github.com:apollographql/router.git
   544f8f619..a83fb721f  1.123.456 -> 1.123.456
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 171 bytes | 171.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:apollographql/router.git
 * [new tag]             v1.123.456-rc.0 -> v1.123.456-rc.0
publish the crates:
cargo publish -p apollo-federation@1.123.456-rc.0
cargo publish -p apollo-router@1.123.456-rc.0
Success!
```

Publishing crates has to be done manually for now.

## Creating the final release PR

```
Select next release step
Next step?:
  create a prerelease
> create the final release PR
```

Then:

```
Creating the final release PR
Already on '1.123.456'
Your branch is up to date with 'origin/1.123.456'.
From github.com:apollographql/router
 * branch                1.123.456  -> FETCH_HEAD
Already up to date.
Switched to a new branch 'prep-1.123.456'
updating Cargo.toml files
    Upgraded apollo-federation from 1.123.456-rc.0 to 1.123.456
Updated dependency apollo-router from =1.123.456-rc.0 to =1.123.456
    Upgraded apollo-router from 1.123.456-rc.0 to 1.123.456
    Upgraded apollo-router-scaffold from 1.123.456-rc.0 to 1.123.456
    Upgraded apollo-router-benchmarks from 1.123.456-rc.0 to 1.123.456
replace in file: "./apollo-router-scaffold/templates/base/Cargo.template.toml"
replace in file: "./apollo-router-scaffold/templates/base/xtask/Cargo.template.toml"
updating lock file
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/geal/dev/router/apollo-router-scaffold/scaffold-test/Cargo.toml
workspace: /home/geal/dev/router/Cargo.toml
warning: /home/geal/dev/router/apollo-router/Cargo.toml: version requirement `=0.5.27+v2.8.1` for dependency `router-bridge` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /home/geal/dev/router/fuzz/Cargo.toml: version requirement `=0.5.27+v2.8.1` for dependency `router-bridge` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
    Blocking waiting for file lock on package cache
   Compiling apollo-router v1.123.456 (/home/geal/dev/router/apollo-router)
    Checking apollo-federation v1.123.456 (/home/geal/dev/router/apollo-federation)
    Finished dev [unoptimized + debuginfo] target(s) in 29.43s
checking compliance
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `xtask/target/debug/xtask check-compliance`
advisories ok, bans ok, licenses ok, sources ok
Success!
updating install script
replace in file: "./scripts/install.sh"
updating helm charts
replace in file: "./helm/chart/router/Chart.yaml"
replace in file: "./helm/chart/router/Chart.yaml"
INFO[2024-06-24T19:15:20+02:00] Found Chart directories [router]             
INFO[2024-06-24T19:15:20+02:00] Generating README Documentation for chart router 
updating docs
replace in file: "./docs/source/containerization/docker.mdx"
replace in file: "./docs/source/containerization/kubernetes.mdx"
replace in file: "./docs/source/containerization/kubernetes.mdx"
updating docker files
replace in file: "./dockerfiles/tracing/docker-compose.zipkin.yml"
replace in file: "./dockerfiles/tracing/docker-compose.datadog.yml"
replace in file: "./dockerfiles/tracing/docker-compose.jaeger.yml"
finalizing changelog
Deleted "/home/geal/dev/router/.changesets/config_bryn_improve_custom_metrics_value_usability.md"
Deleted "/home/geal/dev/router/.changesets/maint_geal_isolate_hyper_0_14.md"
Deleted "/home/geal/dev/router/.changesets/fix_bnjjj_fix_5448.md"
Deleted "/home/geal/dev/router/.changesets/fix_geal_update_router_bridge4.md"
Deleted "/home/geal/dev/router/.changesets/fix_geal_update_router_bridge4-2.md"
Deleted "/home/geal/dev/router/.changesets/maint_bryn_demand_control_studio_traces.md"
Deleted "/home/geal/dev/router/.changesets/feat_bnjjj_add_operation_name_router_selector.md"
Deleted "/home/geal/dev/router/.changesets/feat_rhai_status_code_on_a_router_response.md"
Deleted "/home/geal/dev/router/.changesets/maint_geal_everything_subgraph.md"
Deleted "/home/geal/dev/router/.changesets/feat_local_safelist.md"
prep release branch created
**MANUALLY CHECK AND UPDATE** the `federation-version-support.mdx` to make sure it shows the version of Federation which is included in the `router-bridge` that ships with this version of Router.
 This can be obtained by looking at the version of `router-bridge` in `apollo-router/Cargo.toml` and taking the number after the `+` (e.g., `router-bridge@0.2.0+v2.4.3` means Federation v2.4.3).
Make local edits to the newly rendered `CHANGELOG.md` entries to do some initial editoral.

        These things should have *ALWAYS* been resolved earlier in the review process of the PRs that introduced the changes, but they must be double checked:
    
         - There are no breaking changes.
         - Entries are in categories (e.g., Fixes vs Features) that make sense.
         - Titles stand alone and work without their descriptions.
         - You don't need to read the title for the description to make sense.
         - Grammar is good.  (Or great! But don't let perfect be the enemy of good.)
         - Formatting looks nice when rendered as markdown and follows common convention.
Success!
```


next step is another round of `git add -up .`:

```
please check the changes and add them with `git add -up .`

[prep-1.123.456 103bfe1cd] prep release: v1.123.456
 24 files changed, 190 insertions(+), 168 deletions(-)
 delete mode 100644 .changesets/config_bryn_improve_custom_metrics_value_usability.md
 delete mode 100644 .changesets/feat_bnjjj_add_operation_name_router_selector.md
 delete mode 100644 .changesets/feat_local_safelist.md
 delete mode 100644 .changesets/feat_rhai_status_code_on_a_router_response.md
 delete mode 100644 .changesets/fix_bnjjj_fix_5448.md
 delete mode 100644 .changesets/fix_geal_update_router_bridge4-2.md
 delete mode 100644 .changesets/fix_geal_update_router_bridge4.md
 delete mode 100644 .changesets/maint_bryn_demand_control_studio_traces.md
 delete mode 100644 .changesets/maint_geal_everything_subgraph.md
 delete mode 100644 .changesets/maint_geal_isolate_hyper_0_14.md
a
Enumerating objects: 58, done.
Counting objects: 100% (58/58), done.
Delta compression using up to 16 threads
Compressing objects: 100% (27/27), done.
Writing objects: 100% (30/30), 5.20 KiB | 887.00 KiB/s, done.
Total 30 (delta 20), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (20/20), completed with 20 local objects.
remote: 
remote: Create a pull request for 'prep-1.123.456' on GitHub by visiting:
remote:      https://github.com/apollographql/router/pull/new/prep-1.123.456
remote: 
remote: GitHub found 12 vulnerabilities on apollographql/router's default branch (7 high, 4 moderate, 1 low). To find out more, visit:
remote:      https://github.com/apollographql/router/security/dependabot
remote: 
To github.com:apollographql/router.git
 * [new branch]          prep-1.123.456 -> prep-1.123.456
Branch 'prep-1.123.456' set up to track remote branch 'prep-1.123.456' from 'origin'.
Warning: 35 uncommitted changes

Creating pull request for prep-1.123.456 into 1.123.456 in apollographql/router

https://github.com/apollographql/router/pull/5520
Success!
```

get feedback from the team about the prep release PR

```
Select next release step
Next step?:
  create a prerelease
> finish the release process
```

```
Next step?: finish the release process
Merging the final release PR
Wait for the pre PR to merge into the release PR
Success!
```

```
Switched to branch '1.123.456'
Your branch is up to date with 'origin/1.123.456'.
From github.com:apollographql/router
 * branch                1.123.456  -> FETCH_HEAD
Already up to date.
✓ Pull request apollographql/router#5519 is marked as "ready for review"
release PR marked as ready
✓ Pull request apollographql/router#5519 will be automatically merged when all requirements are met
Wait for the release PR to merge into main
Success!
```

```
Tagging and releasing
Switched to branch 'main'
Your branch is behind 'origin/main' by 328 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
remote: Enumerating objects: 34, done.
[...]
Creating pull request for main into dev in apollographql/router

https://github.com/apollographql/router/pull/5521
dev reconciliation PR created
reconciliation PR URL: : https://github.com/apollographql/router/pull/5521

✓ Pull request apollographql/router#5521 will be automatically merged when all requirements are met
🗣️ **Solicit approval from the Router team, wait for the reconciliation PR to pass CI and auto-merge into `dev`**
⚠️ **Wait for `publish_github_release` on CircleCI to finish on this job before continuing.** ⚠️
Success!
```


```
Updating release notes
manually publish the crates:
cargo publish -p apollo-federation@1.123.456
cargo publish -p apollo-router@1.123.456
Success!
```

The process is done

**Comment by abernix** [comment]
Q: Is `.release-state.json` meant to be checked in?

**Comment by Geal** [comment]
No. I should add it to the .gitignore

**Review by abernix — APPROVED** [review]
My main question will be curiosity around how this works with multiple concurrent releases going on.  I have slight inclination to say that perhaps GitHub itself should be used as the source of state rather than a file, but that's a later problem.

**Review by o0Ignition0o — APPROVED** [review]

**Pull request merged**
