### PR TITLE
relax variables selection for subgraph queries

### LINKED ISSUE #298: subgraph queries with empty entities should not be sent
using the federation examples, if I do the following query with `topProductsFirst = 0`:

```graphql
query ExampleQuery($topProductsFirst: Int) {
  topProducts(first: $topProductsFirst) {
    name
    inStock
    reviews {
      body
    }
  }
}
```

I would expect one subgraph query to the products subgraph, that would return an empty list, and then the router would return an empty list.

What happens instead:
- req to products: `query($topProductsFirst:Int){topProducts(first:$topProductsFirst){__typename upc name}}`, variables `{"topProductsFirst": 0}`, returning `{"topProducts": []}`
- req to reviews: `query($representations:[_Any!]!){_entities(representations:$representations){...on Product{reviews{body}}}}`, variables `{"representations": []}`, returning `{"_entities": []}`
- req to inventory: `query($representations:[_Any!]!){_entities(representations:$representations){...on Product{inStock}}}`, variables `{"representations": []}`, returning `{"_entities": []}`

### LINKED ISSUE #744: `not an object` error
There are some queries that will produce a `not an object` error when they should instead return a valid response.
Reproduction steps to follow.

### PR DESCRIPTION
**Pull request by Geal**
Fix #298 
Fix #744

for federated subgraph queries, we encountered multiple issues:
- if we got a null entity from a previous call, selecting data from it
  would return an error and fail the subgraph request. This is invalid,
because for a request like `query { topProducts { reviews { body } } }`
and a products subgraph returning `[ {"upc": 0}, null, { "upc": 2} ]`,
we should do a query to the reviews subgraph for the products 0 and 2
- if the list of representations to query a subgraph is empty, we were
  still doing a HTTP request expecting an empty result

this PR fixes those issues by ignoring selection errors when
creating variables, then canceling the subgraph request if the
representations array is empty

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]

**Comment by Geal** [comment]
that perf test result is suspiciously good: https://github.com/apollographql/router/runs/5740121572
I thought our benchmarks would not be affected by the empty subgraph query fix

**Comment by BrynCooke** [comment]
Perf test please

**Review by BrynCooke — COMMENTED** [review]
Should the errors that got removed still make it in to the error section in the response? I feel that if a subgraph returns something invalid it should show up somewhere.

**Comment by Geal** [comment]
>Should the errors that got removed still make it in to the error section in the response? I feel that if a subgraph returns something invalid it should show up somewhere.

those errors were not really from validating subgraph responses: that part of the code is selecting data from previous subgraph responses to use as variables for a federated subgraph query. So here I only care about getting a valid selection to do the next query, and ignore the rest. Data is properly validated and filtered later on the entire response in `Query::format_response`.

In the future though we could add proper validation of subgraph responses. That requires building selections like in `format_response` but for all the subgraph queries returned by the query plan

**Comment by BrynCooke** [comment]
Created follow up: https://github.com/apollographql/router/issues/761

**Pull request merged**
