### PR TITLE
GraphOS Enterprise: operation limits

### PR DESCRIPTION
**Pull request by SimonSapin**
You can define operation limits in your router's configuration to reject potentially malicious requests. An operation that exceeds _any_ specified limit is rejected.

You define operation limits in your router's [YAML config file](https://www.apollographql.com/docs/router/configuration/overview#yaml-config-file), like so:

```yaml
preview_operation_limits:
  max_depth: 100
  max_height: 200
  max_aliases: 30
  max_root_fields: 20
```

See details in operation limits documentation in `docs/source/configuration/operation-limits.mdx` and soon at https://www.apollographql.com/docs/router/configuration/operation-limits.

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [x] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [ ] Manual Tests

**Exceptions**

Compatibility: the new parser limit is enabled by default, operations larger than 15_000 tokens will be rejected. This affects ~0.1% of one corpus of 2.5 million known production GraphQL operations. Affected graphs should configure the limiter higher (and consider making smaller queries, as huge ones are likely expensive to execute.)

### CODE REVIEW

**Comment by BrynCooke** [comment]
I was under the impression we were trying to avoid using top level names that match our lifecycle stages. e.g. router and supergraph as this potentially causes confusion as some plugins also use these names to indicate that they are affecting such stages.

Also reading yaml from root to leaf should say what it does.

`supergraph->limits` implies limiting the supergraph, but the feature is `operational->limits`

**Comment by SimonSapin** [comment]
I put the new `limits` config section under the existing `supergraph` section because that’s where are some other config related to GraphQL semantics: `defer_support` and `introspection`. I interpret the `supergraph` config section as "related to federation" more than specifically the lifecycle stage.

That said I’m happy to move this new `limits` section elsewhere. What do you think would be a better location?

**Comment by abernix** [comment]
test failure?

**Comment by SimonSapin** [comment]
This test listens to 127.0.0.1:2828 then tries to connect to it. The error `trying to connect: tcp connect error: Connection refused (os error 111)` looks flaky, I’ve retried the CI run.

**Review by abernix — APPROVED** [review]

**Pull request merged**
