### PR TITLE
configurable client identification headers

### LINKED ISSUE #426: client identity: allow configuring default header names
[Client Segmentation](https://www.apollographql.com/docs/studio/metrics/client-awareness/#using-apollo-server-and-apollo-client) is supported by the router. However, this mechanism also support [configuration of the headers](https://www.apollographql.com/docs/studio/metrics/client-awareness/#advanced-apollo-server-configuration) used to identify clients. The router does not support this configurability and only recognises the default header names.

Should we replicate this behaviour into the router or is it reasonable to require clients to use the specified default names?

### PR DESCRIPTION
**Pull request by Geal**
Fix #426

### CODE REVIEW

**Comment by Geal** [comment]
I am not sure about putting it in spaceport, maybe this could live in the root configuration object. Especially considering it interacts with CORS #127

**Comment by garypen** [comment]
> I am not sure about putting it in spaceport, maybe this could live in the root configuration object. Especially considering it interacts with CORS #127

If it wasn't for CORS, it would definitely only be a spaceport concern.

Perhaps we need to have a default CORS configuration that includes whatever headers are set for spaceport as part of default allowed headers? In which case, it shouldn't be part of the spaceport configuration.

**Review by garypen — APPROVED** [review]
The change looks good as far as it goes, so no problems with the implementation. However, I'm not 100% convinced we should do this because it makes the CORS stuff more complex and feels a bit like a configuration option too far.

I know that's a minority opinion, but ...

**Comment by Geal** [comment]
yup, the CORS configuration as it is cannot meet the use cases we're adding. Between this and the new feature added in https://github.com/apollographql/router/pull/738 where a plugin can add an endpoint, we need CORS to be more flexible and gather info on used headers from multiple  parts of the configuration

**Review by bnjjj — APPROVED** [review]

**Comment by BrynCooke** [comment]
Can we wait until the Otel PR is merged? I am happy to do the changes needed for this PR afterwards.

**Comment by Geal** [comment]
sure, it can wait

**Comment by BrynCooke** [comment]
I'll update this PR tomorrow

**Comment by BrynCooke** [comment]
We've had a couple of large changes under the hood that warrants revisiting:
* The telemetry refactor
* Axum 

I'm gonna pull out the logic for recording the span that spaceport picks up out into the telemetry plugin so we don't need to have the logic in Warp and Axum.

**Comment by BrynCooke** [comment]
Closing as will be superceded by #850

**Pull request closed without merging**
