### PR TITLE
fix the session count metric

### LINKED ISSUE #3485: apollo_router_session_count metric is suspect
As described in: https://github.com/apollographql/router/issues/3392#issuecomment-1645524436 the metric seems to provide odd values at times. A negative session count is often reported and clearly that's not right.

### PR DESCRIPTION
**Pull request by Geal**
Fix #3485 

using a counter for the session count meant that sometimes, the counter is reset to 0 on the metric collector side while the router has active sessions, which means that the next time a session is closed, the counter will send -1 and the metric will be negative. By storing the session count in an atomic, we can make sure to always keep the right( value in the router and have it survive across configuration reloads

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

**Comment by BrynCooke** [comment]
Sorry, let's put this off until after the otel update merges. There's going to be merge conflicts if we do this now. 

I agree that the PR will fix things.

**Review by bnjjj — APPROVED** [review]

**Comment by Geal** [comment]
@BrynCooke no rush on this, just a status update: shall I update this to current dev and make it mergeable now, or wait for the work on #3226 to end?

**Comment by bnjjj** [comment]
feel free to merge @Geal it won't affect our telemetry PR

**Review by garypen — COMMENTED** [review]
Very nice!

I think the docs will need to be updated to document the change to gauge.

**Comment by Geal** [comment]
there's an issue with the active session count that I cannot solve. In every test it fails with `panicked at 'attempt to subtract with overflow', apollo-router/src/axum_factory/axum_http_server_factory.rs:593:33`, while there's clearly been a write to the atomic before, with the same kind of ordering

**Comment by garypen** [comment]
> there's an issue with the active session count that I cannot solve. In every test it fails with `panicked at 'attempt to subtract with overflow', apollo-router/src/axum_factory/axum_http_server_factory.rs:593:33`, while there's clearly been a write to the atomic before, with the same kind of ordering

https://stackoverflow.com/questions/50631189/why-are-const-atomic-variables-not-updated-but-static-atomic-variables-are

If you make the Atomic `static` the tests start passing.

**Comment by Geal** [comment]
yup, that worked!

**Comment by Geal** [comment]
the last remaining issue here is that `apollo_router_session_count_total` is recorded, while `apollo_router_session_active` is not, and I cannot figure out whyn they're both gauges of the same type.

They both go through

https://github.com/apollographql/router/blob/dev/apollo-router/src/metrics/layer.rs#L248

and

https://github.com/apollographql/router/blob/dev/apollo-router/src/metrics/layer.rs#L152-L159

but only the total metric ends up in prometheus

**Comment by BrynCooke** [comment]
This PR has been around for a while now. I'm OK with merging it if we think it's working.

Longer term we'll be deprecating this metric in favor of https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserveractive_requests. 

At this point we'll be allowing configuration of metrics in the telemetry plugin, and we'll need to do the work to move it before any other layers.

**Comment by Geal** [comment]
@BrynCooke there's still the issue from my previous comment, where `apollo_router_session_active` does not appear in the tests, while the other metric does. I still don't understand why, they're written in the same way

**Comment by Geal** [comment]
I tried to fix the test again but couldn't. I validated manually again that the `apollo_router_session_active` metric is generated and available through prometheus, it just does not appear in the metrics reloading test. Since it will soon be deprecated, I will just remove the failing test([c973be2](https://github.com/apollographql/router/pull/3787/commits/c973be22c71127bd6616f049862abfc888d42139)) and move on, there's no need to waste more time on this

**Pull request merged**
