### PR TITLE
Request retries for subgraph queries

### PR DESCRIPTION
**Pull request by Geal**
Fix: #338 
Fix: #1956

### CODE REVIEW

**Comment by Geal** [comment]
I added some configuration options, marked as experimental, so we can move forward on this and at least have some form of retries, before we settle on the policy configuration format.

**Review by o0Ignition0o — APPROVED** [review]
Can we open a followup issue on documentation? I think I have an intuition on how to customize it, but it s all still fuzzy to me

**Review by BrynCooke — APPROVED** [review]
Approved, but I do think documentation should be added as part of this PR.

**Review by bnjjj — APPROVED** [review]

**Comment by bnjjj** [comment]
@Geal On my side for logging and tracing I wrote the documentation in the related section. For tracing in tracing.mdx for example. And just mark it as experimental

**Comment by bnjjj** [comment]
@Geal cf https://github.com/apollographql/router/pull/2040/commits/6dc13330f5e96e475ad3f0b748a0201de2afad69

**Comment by Geal** [comment]
alright, there's docs now. I feel like the traffic shaping doc could benefit from longer explanations of each feature, and maybe a description of their order and interaction

**Pull request merged**
