### PR TITLE
Fix generation of subscription traces for Apollo reporting

### PR DESCRIPTION
**Pull request by bonnici**
Fixes the generation of subscription traces that are sent to Apollo usage reporting.

Fixes https://github.com/apollographql/router/issues/4339

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [x] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [x] Manual Tests

**Exceptions**

I performed manual testing by starting up a subscription-enabled subgraph and publishing a schema with a subscription operation. I then sent a subscription request using Curl:
```
curl 'http://localhost:4000/' -v \
  -H 'accept: multipart/mixed; boundary="graphql"; subscriptionSpec=1.0, application/json' \
  -H 'content-type: application/json' \
  --data-raw '{"query":"subscription ExampleSubFixedRouter { numberIncremented }"}'
```

And the subscription trace was visible in studio: https://studio-staging.apollographql.com/graph/Nick-Subscription-Test/variant/current/insights?insightsTab=operations&query=a4ccc61b2546065c4c3c26748b3913d81c395a72&queryName=ExampleSubFixedRouter&range=lastHour&tab=traces&trace=Nick-Subscription-Test~2023%3A12%3A06T05%3A44~efa80f651708d467b6060a0e4496cdef963fa90c31d65f4095e3e65cf4489093&traceBucket=115

SCR-20231206-nxjf

There is still an open question about whether or not the trace should end after the initial subscription registration rather than ending when the subscription was terminated. The subgraph span in the subscription request also is currently missing FTv1 data even with tracing set to `always_on`, so we are also missing the subgraph timing data in the trace. But with this fix, we at least get a visible trace in studio and it matches the OTel version of the trace.

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by bonnici** [comment]
I'm putting this back in WIP since I just noticed we don't get FTV1 spans for subscriptions even with this change.

**Comment by bonnici** [comment]
Making the PR ready for review again because I confirmed that the `apollo_private.ftv1` attribute is missing on the subgraph fetch span with subscriptions, so the missing subgraph timing is a larger issue that isn't related to the construction of apollo protobuf traces and that's another thing we'd need to fix in a separate issue.

**Review by bnjjj — APPROVED** [review]

**Comment by bnjjj** [comment]
FYI @bonnici the ftv1 attribute can be easily added [here](https://github.com/apollographql/router/blob/dev/apollo-router/src/query_planner/execution.rs#L205:L205) and to fetch it I think you can add code [here](https://github.com/apollographql/router/blob/dev/apollo-router/src/query_planner/subscription.rs#L272C1-L272C1) to get data from `response.body().extensions` and directly add it in span attributes using something like `Span::current().record("apollo_private.ftv1", ftv1.as_str());` . I think you can even re-use this function https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/mod.rs#L1882:L1882

**Comment by bonnici** [comment]
@bnjjj thank you! I'll add that info as a note to the follow-up story. I timeboxed a bit of time to try to add it to this PR but got a bit lost in the code.

**Pull request merged**
