### PR TITLE
docs: rename "client awareness" and add to sidebar

### PR DESCRIPTION
**Pull request by rkoron007**

### CODE REVIEW

**Comment by EverlastingBugstopper** [comment]
should this also include a redirect from the old endpoint to the new one? i think if we merge this as is - https://www.apollographql.com/docs/router/managed-federation/client%20awareness/ will start returning 404s

**Comment by rkoron007** [comment]
Oh, that's a great point @EverlastingBugstopper! I added that redirect :)

**Review by o0Ignition0o — APPROVED** [review]
LGTM!

Most of the team is probably already enjoying their weekend, would you mind us merging it next week?

**Comment by rkoron007** [comment]
No problem at all, take your time!

**Comment by EverlastingBugstopper** [comment]
thanks @rkoron007!

**Pull request merged**
