### PR TITLE
Added extraEnvVars to helm values.yaml

### PR DESCRIPTION
**Pull request by LockedThread**
## Why?
I was trying to deploy Router on my kubernetes cluster with a local schema (not managed) and I was unable to do so without additional environmental variables. 

## Fix
I submitted this PR to solve this by adding 5 more values.yaml fields for extra environmental variables & volumes. The additional fields I added are considered very common and are on every helm chart on the [Bitnami repository](https://github.com/bitnami/charts/). I hope to see my changes implemented.

I wasn't sure what else I should update documentation wise since it's not related to the actual project code. If you'd like to me update something lmk.

### CODE REVIEW

**Review by garypen — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. It looks good. A couple of (hopefully) small requests please:
 - Could you update the helm docs to reflect this change? (https://github.com/norwoodj/helm-docs)
 - Could you rename extraEnvVarsConfigMap to extraEnvVarsCM?

(To update the docs, install a `helm-docs` release and run it in the helm/chart/router directory.)

bitnami specifies extraEnvVarsCM, so we should maintain consistency.

**Comment by LockedThread** [comment]
> 

Yeah I'll get that done.

**Comment by LockedThread** [comment]
You guys should get a github action that does helm docs for you, I have that for my org's chart repo.

**Review by garypen — APPROVED** [review]
Thanks for this contribution.

**Comment by garypen** [comment]
> You guys should get a github action that does helm docs for you, I have that for my org's chart repo.

We use CircleCI and you are right that we could be [better about generating/maintaining documentation](https://github.com/apollographql/router/labels/documentation). I think things will improve here soon. Thanks for doing the manual generation for now.

**Pull request merged**
