### PR TITLE
Move `curl` dependency to separate layer in Docker image

### PR DESCRIPTION
**Pull request by abernix**
The `curl` command is only used in the image we produce today for the sake
of downloading dependencies.  It is never used after that, but we can move
it to a separate layer to further remove it from the image.

Ref: https://github.com/apollographql/router/issues/3144

### CODE REVIEW

**Review by garypen — COMMENTED** [review]
Would it be simpler to `apt remove curl` (+ whatever else we want to remove) after we finish using it?

**Comment by abernix** [comment]
I could do that, but creating the separation seemed to me like it created a more defensible future-proof pattern that would prevent things from bleeding/left-over in the final image.

Do I need to also update `Dockerfile.repo`?

**Comment by garypen** [comment]
> I could do that, but creating the separation seemed to me like it created a more defensible future-proof pattern that would prevent things from bleeding/left-over in the final image. Tbh, I also wasn't confident it wouldn't leave something behind (like configuration files, etc.)
> 

I think we should be able to depend on `apt remove` and leaving around configuration files is very unlikely to be a security fail, but ...

> Do I need to also update `Dockerfile.repo`?

Yes. Just don't install `curl`.

**Comment by abernix** [comment]
I've updated `Dockerfile.repo`, too.

**Review by Geal — APPROVED** [review]

**Review by SimonSapin — APPROVED** [review]

**Comment by abernix** [comment]
@garypen While my skepticism around `apt remove`'s completeness is certainly worth challenging, I'd still claim there's a more defensive approach by creating a clear delineation between stages.  A future world may find someone introducing an addition to `apt install` that isn't `apt curl` (idk, `protoc`, or something like that) but forget to add it to `apt remove`.   I'd claim this avoids that state by creating a very intentional divide (a pattern which is used in the `Dockerfile.repo` file, as well, but wasn't used here prior to this edit).  That divide puts the important burden on the person making a change that requires they intentionally put things into the output, rather than opting certain things out.

I am going to leave the change as I have it right now unless you think that defence isn't defendable or flawed. :smile:

**Review by garypen — APPROVED** [review]

**Pull request merged**
