### PR TITLE
refresh query plan expiration on GET

### PR DESCRIPTION
**Pull request by Geal**
Fix https://github.com/apollographql/router/issues/4473
We want the query plan cache to act like a LRU, so if a TTL is set in its Redis configuration, we will reset the plan cache key's current expiration when reding it

~unclear to me here: should we instead make it an option on the common redis configuration type? We may want to control that behaviour for APQ and introspection too~ This is now part of the common redis configuration and defaults to true. For entity caching, this option is disabled, as the cache will manage TTL directly

Tests now require REdis 7. Otherwise you will get the error "ERR unknown command `EXPIRETIME`"

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by lleadbet** [comment]
> unclear to me here: should we instead make it an option on the common redis configuration type? We may want to control that behaviour for APQ and introspection too

If possible. The "TTL reset" mechanism is helpful for this use-case imo.

**Review by garypen — COMMENTED** [review]
Is there any way we can test this functionality by extending our existing redis integration tests?
also: config feature => changelog?

**Comment by Geal** [comment]
Probably yes, we can check a key's expiration by querying redis in the test

**Review by bnjjj — APPROVED** [review]
Missing the changelog but LGTM

**Comment by Geal** [comment]
there is now a test in f08b3ad90. Integration tests will require Redis 7 from now on, to have access to the `EXPIRETIME` command

**Pull request merged**
