### PR TITLE
Expose executable::Opt

### LINKED ISSUE #3486: Expose executable::Opt to allow augmentation with external cli
**Is your feature request related to a problem? Please describe.**
I am trying to augment apollo router into a small wrapping cli program, it is not currently possible to make the router play nicely while also being able to use clap in a separate context.

**Describe the solution you'd like**
Please could you make `executable::Opt` public?

**Additional context**
It's possible to augment multiple `Parser`s arguments into a single command and match it's arguments then instantiate both structs independently from the matched args.

With this minor change it would allow additional arguments be provided to an encapsulating custom binary, which can then instantiate the `executable::Opt` struct and pass it to the `Executable` builder via `Executable::builder().cli_args(*opt*)`

### PR DESCRIPTION
**Pull request by sonewman**
This is the change I would be proposing in the issue I raised 3 weeks ago https://github.com/apollographql/router/issues/3486. I have not recieved any feedback so i thought i'd take a chance and raise as a PR to see if i can get get this merged or atleast get some feedback

Fixes #3486

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

**Comment by sonewman** [comment]
Hi, i don't know if there is anyone i can get feedback from? i'm not quite sure what "tests", "documentation" or "performance" related things i would need to address... this change is imo very trivial, it is just making the cli opt's public so they can be accessed when using the crate as a lib. All the other arguments to the Executable are already public barring this one. I don't know if that was a deliberated intention or just oversight. But otherwise i don't see how this change would have any consequential affects to functionality and performance at all.

**Comment by o0Ignition0o** [comment]
Hi @sonewman, it's nice to meet you!

The perf runs make sure changesets don't degrade the RPS / latency the router operates within.

> All the other arguments to the Executable are already public barring this one. I don't know if that was a deliberated intention or just oversight.

I'll check with the team and get back to you asap

**Comment by abernix** [comment]
@sonewman I left you a question on the issue that you opened a few days ago: https://github.com/apollographql/router/issues/3486#issuecomment-1678971585.  Apologies that it takes a couple weeks to get to issues sometimes.  Could we pop back over to the issue and discuss that question a bit?  We can come back to the PR once we're aligned. (@o0Ignition0o if you don't mind joining us over there, we can figure out the direction?)

**Comment by abernix** [comment]
I'm going to close this as it wouldn't be something we'd be interested in introducing right now without a lot more testing considerations introduced and a commitment to this being part of our public API, which we're not yet ready to do.

**Pull request closed without merging**
