### PR TITLE
set a default TTL for query plans

### PR DESCRIPTION
**Pull request by Geal**
Fix https://github.com/apollographql/router/issues/4473

This sets a default TTL for query plan caches, because right now the default is sto store query plans indefinitely, which does not make sense because they change with schema updates.
The PR is a bit verbose because to add that new default, we need to create a redundant structure for redis configuration (I tried const generics but serde won't support them)

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by BrynCooke** [comment]
I think there should be some sort of documentation update associated with this. @shorgi can we add a table for the options with defaults?

**Comment by Geal** [comment]
there is some documentation now

**Comment by Geal** [comment]
actually maybe it would make sense to have a default expiration for APQ too :thinking:

**Comment by Geal** [comment]
@BrynCooke @bnjjj @o0Ignition0o could I get a review for this PR? This has waited for 3 weeks already

**Review by BrynCooke — APPROVED** [review]

**Pull request merged**
