### PR TITLE
Entity cache fix: update the cache key with private info on the first call

### PR DESCRIPTION
**Pull request by Geal**
This adds a test for private information caching and fixes an issue where private data was stored at the wrong key, so it did not appear to be cached

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

[ROUTER-109]: https://apollographql.atlassian.net/browse/ROUTER-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ROUTER-285]: https://apollographql.atlassian.net/browse/ROUTER-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bnjjj — APPROVED** [review]

**Review by BrynCooke — DISMISSED** [review]
This looks like a fix rather than just adding a test, so let's have a changelog unless this is completely new functionality.

**Review by garypen — COMMENTED** [review]
This looks like a fix to the existing entity caching functionality, so we should have a changelog.

**Comment by Geal** [comment]
what was blocking the writing of the changelog?

**Comment by Geal** [comment]
there's a changeset now, so barring any new info, I'll merge this, because we have people who are trying out the private info caching

**Pull request merged**
