### PR TITLE
Add QueryPlannerConfig to QueryPlan key

### PR DESCRIPTION
**Pull request by fotoetienne**
Addresses Issue #5093

This is an incomplete PR (doesn't build yet) that demonstrates a proposed solution to Issue #5093

### CODE REVIEW

**Review by Geal — CHANGES_REQUESTED** [review]
this sounds ok, the only thing missing right now is hashing the planner config along with the metadata and others at https://github.com/apollographql/router/pull/5094/files#diff-560bfe015eb92a1ce9b2b1e2282f58d41574eeb3cb1d94385b5c8b96544e8b1cR546
(This part generates the redis cache key)

Then probably some tests will need to be updated, in particular the redis integration test. Do you want me to get it to the finish line or do you want to attempt it?

**Comment by fotoetienne** [comment]
> this sounds ok, the only thing missing right now is hashing the planner config along with the metadata and others at https://github.com/apollographql/router/pull/5094/files#diff-560bfe015eb92a1ce9b2b1e2282f58d41574eeb3cb1d94385b5c8b96544e8b1cR546 (This part generates the redis cache key)
> 
> Then probably some tests will need to be updated, in particular the redis integration test. Do you want me to get it to the finish line or do you want to attempt it?

If you have the bandwidth, that would be great. Thanks!

**Comment by abernix** [comment]
We'll take a look!

**Comment by abernix** [comment]
I'll close this in lieu of https://github.com/apollographql/router/pull/5100 which took a similar approach to solve for the intent of this PR, along with taking some other considerations.  Appreciate you taking the time to do this follow-up and prompting the work, nonetheless. 😄

**Pull request closed without merging**
